(function(){
'use strict';var Qf=function(a,b){return $APP.aa[a]=b},Rf=function(a){return null==a},Sf=function(a){if(null!=a&&null!=a.va)a=a.va(a);else{var b=Sf[$APP.q(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Sf._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.x("IStack.-peek",a);}return a},Tf=function(a){if(null!=a&&null!=a.wa)a=a.wa(a);else{var b=Tf[$APP.q(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Tf._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.x("IStack.-pop",
a);}return a},Uf=function(){},Vf=function(a){if(null!=a&&null!=a.Ta)a=a.Ta(a);else{var b=Vf[$APP.q(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Vf._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.x("IReversible.-rseq",a);}return a},Wf=function(a,b){if(null!=$APP.Lf&&null!=$APP.Lf.xb)$APP.Lf.xb($APP.Lf,a,b);else{var c=Wf[$APP.q(null==$APP.Lf?null:$APP.Lf)];if(null!=c)c.j?c.j($APP.Lf,a,b):c.call(null,$APP.Lf,a,b);else if(c=Wf._,null!=c)c.j?c.j($APP.Lf,a,b):c.call(null,$APP.Lf,
a,b);else throw $APP.x("IWatchable.-add-watch",$APP.Lf);}},Xf=function(a,b){if(null!=a&&null!=a.Sb)a=a.Sb(a,b);else{var c=Xf[$APP.q(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=Xf._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $APP.x("IReset.-reset!",a);}return a},Yf=function(a){return a+1},Zf=function(a){if(null==$APP.ra)throw Error("No *print-fn* fn set for evaluation environment");$APP.ra.call(null,a)},$f=function(){return function(){function a(f,h){return $APP.ua(Rf.h?
Rf.h(f,h):Rf.call(null,f,h))}function b(f){return $APP.ua(Rf.g?Rf.g(f):Rf.call(null,f))}function c(){return $APP.ua(Rf.B?Rf.B():Rf.call(null))}var d=null,e=function(){function f(k,l,m){var n=null;if(2<arguments.length){n=0;for(var p=Array(arguments.length-2);n<p.length;)p[n]=arguments[n+2],++n;n=new $APP.E(p,0,null)}return h.call(this,k,l,n)}function h(k,l,m){return $APP.ua($APP.Vc(Rf,k,l,m))}f.I=2;f.G=function(k){var l=$APP.G(k);k=$APP.J(k);var m=$APP.G(k);k=$APP.Gb(k);return h(l,m,k)};f.s=h;return f}();
d=function(f,h,k){switch(arguments.length){case 0:return c.call(this);case 1:return b.call(this,f);case 2:return a.call(this,f,h);default:var l=null;if(2<arguments.length){l=0;for(var m=Array(arguments.length-2);l<m.length;)m[l]=arguments[l+2],++l;l=new $APP.E(m,0,null)}return e.s(f,h,l)}throw Error("Invalid arity: "+arguments.length);};d.I=2;d.G=e.G;d.B=c;d.g=b;d.h=a;d.s=e.s;return d}()},bg=function(a){var b=ag;return function(){function c(l,m,n){return b.D?b.D(a,l,m,n):b.call(null,a,l,m,n)}function d(l,
m){return b.j?b.j(a,l,m):b.call(null,a,l,m)}function e(l){return b.h?b.h(a,l):b.call(null,a,l)}function f(){return b.g?b.g(a):b.call(null,a)}var h=null,k=function(){function l(n,p,t,v){var y=null;if(3<arguments.length){y=0;for(var A=Array(arguments.length-3);y<A.length;)A[y]=arguments[y+3],++y;y=new $APP.E(A,0,null)}return m.call(this,n,p,t,y)}function m(n,p,t,v){return $APP.Xc(b,a,n,p,t,$APP.P([v]))}l.I=3;l.G=function(n){var p=$APP.G(n);n=$APP.J(n);var t=$APP.G(n);n=$APP.J(n);var v=$APP.G(n);n=$APP.Gb(n);
return m(p,t,v,n)};l.s=m;return l}();h=function(l,m,n,p){switch(arguments.length){case 0:return f.call(this);case 1:return e.call(this,l);case 2:return d.call(this,l,m);case 3:return c.call(this,l,m,n);default:var t=null;if(3<arguments.length){t=0;for(var v=Array(arguments.length-3);t<v.length;)v[t]=arguments[t+3],++t;t=new $APP.E(v,0,null)}return k.s(l,m,n,t)}throw Error("Invalid arity: "+arguments.length);};h.I=3;h.G=k.G;h.B=f;h.g=e;h.h=d;h.j=c;h.s=k.s;return h}()},dg=function(a){var b=/([a-z]+)\(([^)]+)\)\s*/;
if("string"===typeof a)return cg(b,a);throw new TypeError("re-seq must match against a string.");},eg=function(a,b){return new $APP.Fc(null,function(){var c=$APP.F(b);if(c){if($APP.hc(c)){for(var d=$APP.mb(c),e=$APP.K(d),f=new $APP.Hc(Array(e)),h=0;;)if(h<e){var k=$APP.Yb(d,h);k=a.g?a.g(k):a.call(null,k);$APP.u(k)&&(k=$APP.Yb(d,h),f.add(k));h+=1}else break;return $APP.Kc(f.la(),eg(a,$APP.nb(c)))}d=$APP.G(c);c=$APP.Gb(c);return $APP.u(a.g?a.g(d):a.call(null,d))?$APP.R(d,eg(a,c)):eg(a,c)}return null},
null)},fg=function(a){return(null!=a?a.l&134217728||$APP.D===a.oc||(a.l?0:$APP.w(Uf,a)):$APP.w(Uf,a))?(a=Vf(a))?a:$APP.H:$APP.qc($APP.gd,$APP.H,a)},gg=function(a){var b=$APP.Z.j($APP.pa(),$APP.la,!1);Zf($APP.Se(a,b));$APP.u($APP.qa)?(a=$APP.pa(),Zf("\n"),a=($APP.kc.h(a,$APP.ka),null)):a=null;return a},hg=function(a,b){if(a instanceof $APP.fd){var c=a.cc;if(null!=c&&!$APP.u(c.g?c.g(b):c.call(null,b)))throw Error("Validator rejected reference state");c=a.state;a.state=b;if(null!=a.rb)a:for(var d=$APP.F(a.rb),
e=null,f=0,h=0;;)if(h<f){var k=e.J(null,h),l=$APP.Q(k,0,null);k=$APP.Q(k,1,null);k.D?k.D(l,a,c,b):k.call(null,l,a,c,b);h+=1}else if(d=$APP.F(d))$APP.hc(d)?(e=$APP.mb(d),d=$APP.nb(d),l=e,f=$APP.K(e),e=l):(e=$APP.G(d),l=$APP.Q(e,0,null),k=$APP.Q(e,1,null),k.D?k.D(l,a,c,b):k.call(null,l,a,c,b),d=$APP.J(d),e=null,f=0),h=0;else break a;return b}return Xf(a,b)},kg=function(a){null==ig&&(ig=new $APP.fd(0));var b=$APP.Te.g([$APP.z.g("G__"),$APP.z.g(jg.h(ig,Yf))].join(""));Wf(b,a)},lg=function(a){this.f=a;
this.value=null;this.l=2147516416;this.C=1},mg=function(a){if("string"===typeof a)return $APP.Fe(/[\x00-\x20]*[+-]?NaN[\x00-\x20]*/,a)?NaN:$APP.Fe(/[\x00-\x20]*[+-]?(Infinity|((\d+\.?\d*|\.\d+)([eE][+-]?\d+)?)[dDfF]?)[\x00-\x20]*/,a)?parseFloat(a):null;throw Error(["Expected string, got: ",$APP.z.g(null==a?"nil":$APP.q(a))].join(""));},ng=function(a,b,c){kg(function(d,e,f,h){d=$APP.kc.h(f,a);var k=$APP.kc.h(h,a);return $APP.M.h(d,k)?null:setTimeout(function(){return $APP.Uc(b,k,c)},0)})},og=function(a){for(var b=
[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;ng(arguments[0],arguments[1],2<b.length?new $APP.E(b.slice(2),0,null):null)},pg=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;a:{c=arguments[0];d=arguments[1];var e=arguments[2];for(b=3<b.length?new $APP.E(b.slice(3),0,null):null;;)if(c[d]=e,$APP.F(b))d=$APP.G(b),e=$APP.G($APP.J(b)),b=$APP.J($APP.J(b));else break a}},qg=function(a){return"string"===typeof a?document.getElementById(a):
a},rg=function(a){return $APP.$e(qg(a),"classList")},sg=function(a,b){a=rg(a);b=$APP.F(b);for(var c=null,d=0,e=0;;)if(e<d){var f=c.J(null,e);a.add(f);e+=1}else if(b=$APP.F(b))c=b,$APP.hc(c)?(b=$APP.mb(c),e=$APP.nb(c),c=b,d=$APP.K(b),b=e):(b=$APP.G(c),a.add(b),b=$APP.J(c),c=null,d=0),e=0;else break},ug=function(){var a=$APP.P([tg,"none"]),b=qg("fullscreen"),c=$APP.F(a);$APP.G(c);c=$APP.J(c);$APP.G(c);for($APP.J(c);;){c=$APP.F(a);a=$APP.G(c);c=$APP.J(c);var d=$APP.G(c);c=$APP.J(c);b.setAttribute($APP.Ee(a),
$APP.z.g(d));if($APP.F(c))a=c;else break}},vg=function(a,b){a=qg(a);pg(a,"textContent",b);return a},wg=function(a,b){a=qg(a);b=$APP.F(b);for(var c=null,d=0,e=0;;)if(e<d){var f=c.J(null,e);a.append(f);e+=1}else if(b=$APP.F(b))c=b,$APP.hc(c)?(b=$APP.mb(c),e=$APP.nb(c),c=b,d=$APP.K(b),b=e):(b=$APP.G(c),a.append(b),b=$APP.J(c),c=null,d=0),e=0;else break},xg=function(a,b){b=$APP.ec($APP.G(b))?new $APP.V(null,2,5,$APP.W,[$APP.G(b),$APP.Gb(b)],null):new $APP.V(null,2,5,$APP.W,[null,b],null);var c=$APP.Q(b,
0,null);b=$APP.Q(b,1,null);a=document.createElement(a);c=$APP.F(c);for(var d=null,e=0,f=0;;)if(f<e){var h=d.J(null,f),k=$APP.Q(h,0,null);h=$APP.Q(h,1,null);$APP.M.h(k,$APP.Bf)?sg(a,$APP.Y.h($APP.z,$APP.dc(h)?eg($f(),h):$APP.R(h,null))):a.setAttribute($APP.Ee(k),$APP.z.g(h));f+=1}else if(c=$APP.F(c))$APP.hc(c)?(e=$APP.mb(c),c=$APP.nb(c),d=e,e=$APP.K(e)):(e=$APP.G(c),d=$APP.Q(e,0,null),e=$APP.Q(e,1,null),$APP.M.h(d,$APP.Bf)?sg(a,$APP.Y.h($APP.z,$APP.dc(e)?eg($f(),e):$APP.R(e,null))):a.setAttribute($APP.Ee(d),
$APP.z.g(e)),c=$APP.J(c),d=null,e=0),f=0;else break;b=$APP.F(b);c=null;for(e=d=0;;)if(e<d)f=c.J(null,e),$APP.dc(f)?wg(a,f):wg(a,$APP.P([f])),e+=1;else if(b=$APP.F(b))c=b,$APP.hc(c)?(b=$APP.mb(c),e=$APP.nb(c),c=b,d=$APP.K(b),b=e):(b=$APP.G(c),$APP.dc(b)?wg(a,b):wg(a,$APP.P([b])),b=$APP.J(c),c=null,d=0),e=0;else break;return a},yg=function(a,b,c){qg(a).addEventListener($APP.Ee(b),c,null)},zg=function(a){a=$APP.Pf.g?$APP.Pf.g(a):$APP.Pf.call(null,a);$APP.u(null)&&a.stereo(null);return a.play()},Ag=function(a){console.log("set-sound-on",
a);$APP.u(a)?rg("sound").add("active"):rg("sound").remove("active");return $APP.Nf.Howler.mute($APP.ua(a))},Cg=function(){yg("sound",$APP.Af,function(){return jg.D($APP.Lf,Bg,$APP.xf,$APP.ua)});og($APP.xf,Ag);jg.D($APP.Lf,$APP.Z,$APP.xf,!0)},Dg=function(a){if($APP.u(a))return rg("fullscreen").add("active"),qg("wrapper").requestFullscreen().then(function(){return gg($APP.P(["fullscreen: success"]))},function(){return gg($APP.P(["fullscreen: rejected"]))});rg("fullscreen").remove("active");return document.exitFullscreen().then(function(){return gg($APP.P(["fullscreen: success"]))},
function(){return gg($APP.P(["fullscreen: rejected"]))})},Gg=function(){var a=null!=$APP.$e(document,"exitFullscreen"),b=null!=$APP.$e(document,"fullscreenElement");a||ug();a&&(yg("fullscreen",$APP.Af,function(){return jg.D($APP.Lf,Bg,Eg,$APP.ua)}),og(Eg,Dg));jg.j($APP.Lf,$APP.tf,new $APP.r(null,2,[Fg,a,Eg,b],null))},Jg=function(a){return function(b){if(!$APP.u($APP.$e(b,"repeat"))){var c=$APP.$e(b,"ctrlKey"),d=$APP.$e(b,"metaKey");$APP.ua($APP.$e(b,"shiftKey"))&&$APP.ua(c)&&$APP.ua(d)&&(c=function(){switch($APP.$e(b,
"code")){case "ArrowUp":return $APP.Hf;case "Space":return $APP.Ff;case "ArrowLeft":return $APP.Kf;case "ArrowRight":return $APP.If;case "KeyD":return Hg;case "KeyR":return Ig;default:return null}}(),$APP.u(c)&&(b.preventDefault(),jg.D($APP.Lf,$APP.Z,c,a)))}return null}},Kg=function(a,b){return function(c){c.preventDefault();return jg.D($APP.Lf,$APP.Z,a,b)}},Lg=function(a){return $APP.u(a)?$APP.qc(function(b,c){$APP.Q(c,0,null);var d=$APP.Q(c,1,null),e=$APP.Q(c,2,null);c=$APP.Z.j;d=$APP.Ne.g(d);var f=
$APP.Y.h,h=/[\s,]/;e="/(?:)/"===$APP.z.g(h)?$APP.gd.h($APP.wd($APP.R("",$APP.Y.h($APP.z,$APP.F(e)))),""):$APP.wd($APP.z.g(e).split(h));if(1<$APP.K(e))a:for(;;)if(""===(null==e?null:Sf(e)))e=null==e?null:Tf(e);else break a;return c.call($APP.Z,b,d,f.call($APP.Y,mg,e))},$APP.ad,dg(a)):null},Ng=function(a){return $APP.qc(function(b,c){var d=c.g?c.g(a):c.call(null,a);if($APP.u(d)){b=$APP.z.g(b);c=$APP.Ee(c);var e=$APP.z,f=e.g;if($APP.dc(d))a:{var h=new $APP.ja;for(d=$APP.F(d);;)if(null!=d)h.append($APP.z.g($APP.G(d))),
d=$APP.J(d),null!=d&&h.append(" ");else{d=h.toString();break a}}b=[b,c,"(",f.call(e,d),") "].join("")}return b},"",Mg)},Og=function(a){return $APP.qc(function(b,c){var d=$APP.ia(a,c);return $APP.u(d)?$APP.Z.j(b,c,d):b},$APP.ad,Mg)},Qg=function(a,b){return $APP.qc(function(c,d){var e=$APP.Q(d,0,null);d=$APP.Q(d,1,null);return $APP.M.h(e,Pg)?Lg(d):$APP.Z.j(c,e,d)},Og(a),b)},Rg=function(a,b){b=$APP.F(b);for(var c=null,d=0,e=0;;)if(e<d){var f=c.J(null,e);a.appendChild(f);e+=1}else if(b=$APP.F(b))c=b,
$APP.hc(c)?(b=$APP.mb(c),e=$APP.nb(c),c=b,d=$APP.K(b),b=e):(b=$APP.G(c),a.appendChild(b),b=$APP.J(c),c=null,d=0),e=0;else break},Sg=function(a){switch(arguments.length){case 3:return Sg(null,arguments[0],arguments[1],arguments[2]);default:for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;b=new $APP.E(b.slice(4),0,null);return ag.s("circle",$APP.P([$APP.Z.s(arguments[0],Tg,arguments[1],$APP.P([Ug,arguments[2],Vg,arguments[3]])),b]))}},Wg=function(a){switch(arguments.length){case 1:return Wg(null,
arguments[0]);default:for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return Xg(arguments[0],arguments[1],new $APP.E(b.slice(2),0,null))}},Xg=function(a,b,c){return ag.s("polygon",$APP.P([$APP.Z.j(a,Yg,$APP.qc(function(d,e){var f=$APP.Q(e,0,null);e=$APP.Q(e,1,null);return[$APP.z.g(d),$APP.z.g(f),",",$APP.z.g(e)," "].join("")},"",b)),c]))},Zg=function(a){return $APP.u(a)?a.toFixed(2):"-"},$g=function(a){return $APP.u(a)?"ON":"OFF"},eh=function(){console.log(ah);wg("wrapper",
$APP.P([xg("div",$APP.P([new $APP.r(null,1,[bh,"debug"],null),xg("table",$APP.P([xg("tbody",$APP.P([function(){return function c(b){return new $APP.Fc(null,function(){for(;;){var d=$APP.F(b);if(d){if($APP.hc(d)){var e=$APP.mb(d),f=$APP.K(e),h=new $APP.Hc(Array(f));a:for(var k=0;;)if(k<f){var l=$APP.Yb(e,k);l=$APP.Q(l,0,null);l=xg("tr",$APP.P([xg("td",$APP.P([new $APP.r(null,1,[ch,l],null),$APP.Se($APP.P([l]),$APP.pa())])),xg("td",$APP.P([new $APP.r(null,1,[bh,["debug-data-",$APP.z.g(l)].join("")],
null),"-"]))]));h.add(l);k+=1}else{e=!0;break a}return e?$APP.Kc(h.la(),c($APP.nb(d))):$APP.Kc(h.la(),null)}h=$APP.G(d);h=$APP.Q(h,0,null);return $APP.R(xg("tr",$APP.P([xg("td",$APP.P([new $APP.r(null,1,[ch,h],null),$APP.Se($APP.P([h]),$APP.pa())])),xg("td",$APP.P([new $APP.r(null,1,[bh,["debug-data-",$APP.z.g(h)].join("")],null),"-"]))])),c($APP.Gb(d)))}return null}},null)}(dh)}()]))]))]))]))},gh=function(a){if($APP.u(fh.g(a)))for(var b=$APP.F(dh),c=null,d=0,e=0;;)if(e<d){var f=c.J(null,e),h=$APP.Q(f,
0,null),k=$APP.Q(f,1,null);vg(["debug-data-",$APP.z.g(h)].join(""),function(){var n=h.g?h.g(a):h.call(null,a);return k.g?k.g(n):k.call(null,n)}());e+=1}else if(b=$APP.F(b)){c=b;if($APP.hc(c))b=$APP.mb(c),e=$APP.nb(c),c=b,d=$APP.K(b),b=e;else{b=$APP.G(c);var l=$APP.Q(b,0,null),m=$APP.Q(b,1,null);vg(["debug-data-",$APP.z.g(l)].join(""),function(){var n=l.g?l.g(a):l.call(null,a);return m.g?m.g(n):m.call(null,n)}());b=$APP.J(c);c=null;d=0}e=0}else break;return a},jh=function(){og(Hg,function(a){console.log(":debug-toggle",
a);return $APP.u(a)?jg.D($APP.Lf,Bg,fh,hh.h(function(b){if($APP.u(b))eh();else{console.log(ih);var c=qg("wrapper"),d=qg("debug");$APP.u($APP.u(c)?d:c)&&c.removeChild(d)}return b},$APP.ua)):null})},Hh=function(a,b){var c=kh.g(a),d=$APP.Z.j;a=$APP.Z.j(a,lh,b-c);var e=lh.g(a);c=$APP.u($APP.Kf.g(a))?-mh:0;var f=$APP.u($APP.If.g(a))?mh:0;c=nh.g(a)+(c+f);c=c<oh?oh:c>ph?ph:c;e=qh.g(a)+e*c;var h=$APP.u($APP.Hf.g(a))?.01:0,k=rh.g(a);var l=sh.g(a);f=l*(th.g?th.g(k):th.call(null,k))+h*(th.g?th.g(e):th.call(null,
e));h=l*(uh.g?uh.g(k):uh.call(null,k))+h*(uh.g?uh.g(e):uh.call(null,e));k=$APP.W;l=vh.h?vh.h(f,h):vh.call(null,f,h);var m=f*f+h*h;m=wh.g?wh.g(m):wh.call(null,m);l=new $APP.V(null,4,5,k,[l,m,f,-h],null);f=$APP.Q(l,0,null);h=$APP.Q(l,1,null);k=$APP.Q(l,2,null);l=$APP.Q(l,3,null);k=xh.g(a)+k;l=yh.g(a)+l;zh.s(Ah.g(a),$APP.P([Bh,f/Ch*180,Dh,-100*h]));zh.s(Eh.g(a),$APP.P([Bh,e/Ch*180]));zh.s(Fh.g(a),$APP.P([Gh,new $APP.V(null,2,5,$APP.W,[k,l],null)]));a=$APP.Z.s(a,xh,k,$APP.P([yh,l,rh,f,sh,h,qh,e,nh,c]));
return d.call($APP.Z,gh(a),kh,b)},Jh=function(a){var b=$APP.Ne.g([$APP.Ee(a),"-cone"].join(""));return function(c){return jg.h($APP.Lf,function(d){return Bg.$(d,Ih,Bg,a,function(e){if($APP.u(c))return zh.s(d.g?d.g(b):d.call(null,b),$APP.P([tg,""])),zg(a);zh.s(d.g?d.g(b):d.call(null,b),$APP.P([tg,"none"]));var f=$APP.Pf.g?$APP.Pf.g(a):$APP.Pf.call(null,a);f.fade(f.volume(),0,200,e);return null})})}},Lh=function(){og($APP.Kf,Jh($APP.Kf));og($APP.If,Jh($APP.If));og($APP.Hf,Jh($APP.Hf));og($APP.Ff,function(a){return $APP.u(a)?
zg($APP.Ff):null});og(Ig,function(a){return $APP.u(a)?jg.j($APP.Lf,$APP.tf,Kh):null});jg.j($APP.Lf,$APP.tf,Kh)},Qh=function(){var a=$APP.Sa($APP.Lf);a=Mh.g(a);var b=qg("wrapper"),c=$APP.$e(b,"clientWidth");b=$APP.$e(b,"clientHeight");var d=c/2E3;var e=b/1E3;d=d<e?d:e;console.log(Nh,c,"x",b,"\x3d\x3e",d);zh.s(qg("game"),$APP.P([Oh,["0 0 ",$APP.z.g(c)," ",$APP.z.g(b)].join("")]));return zh.s(a,$APP.P([Gh,new $APP.V(null,2,5,$APP.W,[.5*c,.5*b],null),Ph,d]))},$h=function(a,b,c){a=new $APP.r(null,3,[Gh,
new $APP.V(null,2,5,$APP.W,[a,b],null),Bh,c,tg,"none"],null);b=new $APP.r(null,1,[Rh,"yellow"],null);c=$APP.P([Sh(new $APP.r(null,4,[Th,"ry",Uh,"3;6;3",Vh,"100ms",Wh,"indefinite"],null)),Sh(new $APP.r(null,4,[Th,"fill-opacity",Uh,"0.5;1.0;0.5",Vh,"100ms",Wh,"indefinite"],null))]);b=ag.s("ellipse",$APP.P([$APP.Z.s(b,Tg,0,$APP.P([Ug,0,Xh,3,Yh,3])),c]));return Zh(a,b)},ii=function(){var a=ag.s("line",$APP.P([$APP.Z.s(new $APP.r(null,2,[ai,"green",bi,2],null),ci,0,$APP.P([di,0,ei,0,Dh,0]))]));var b=$h(8,
-8,90);var c=$h(-8,-8,-90),d=$h(0,20,0),e=Zh(b,c,d,Wg(new $APP.r(null,3,[ai,"red",bi,3,Rh,"var(--text-color)"],null),new $APP.V(null,5,5,$APP.W,[new $APP.V(null,2,5,$APP.W,[0,-20],null),new $APP.V(null,2,5,$APP.W,[18,12],null),new $APP.V(null,2,5,$APP.W,[12,20],null),new $APP.V(null,2,5,$APP.W,[-12,20],null),new $APP.V(null,2,5,$APP.W,[-18,12],null)],null))),f=Zh(e,a),h=Zh(f,Sg(new $APP.r(null,3,[ai,"green",bi,3,Rh,"none"],null),-1E3,-500,30),Sg(new $APP.r(null,3,[ai,"green",bi,3,Rh,"none"],null),
1E3,-500,30),Sg(new $APP.r(null,3,[ai,"green",bi,3,Rh,"none"],null),1E3,500,30),Sg(new $APP.r(null,3,[ai,"green",bi,3,Rh,"none"],null),-1E3,500,30));b=new $APP.r(null,7,[Mh,h,Fh,f,Eh,e,fi,b,gi,c,hi,d,Ah,a],null);jg.j($APP.Lf,$APP.tf,b);a=vg("game","");b=$APP.P([Mh.g(b)]);wg(a,b);setTimeout(Qh,0)},ki=function(){return $APP.Sa(ji)},li=function li(a,b,c){var e=a.m-2>>>b&31;if(5<b){b-=5;var f=c.i[e];a=li.j?li.j(a,b,f):li.call(null,a,b,f);if(null==a&&0===e)return null;c=$APP.kd(c);c.i[e]=a;return c}if(0===
e)return null;c=$APP.kd(c);c.i[e]=null;return c};$APP.fd.prototype.xb=Qf(11,function(a,b,c){this.rb=$APP.Z.j(this.rb,b,c);return this});$APP.Bc.prototype.wa=Qf(10,function(){return this.ea(null)});$APP.Cc.prototype.wa=Qf(9,function(){throw Error("Can't pop empty list");});
$APP.V.prototype.wa=Qf(8,function(){if(0===this.m)throw Error("Can't pop empty vector");if(1===this.m)return $APP.Va($APP.vd,this.u);if(1<this.m-$APP.ld(this))return new $APP.V(this.u,this.m-1,this.shift,this.root,this.ha.slice(0,-1),null);var a=$APP.nd(this,this.m-2),b=li(this,this.shift,this.root);b=null==b?$APP.W:b;var c=this.m-1;return 5<this.shift&&null==b.i[1]?new $APP.V(this.u,c,this.shift-5,b.i[0],a,null):new $APP.V(this.u,c,this.shift,b,a,null)});
$APP.Md.prototype.wa=Qf(7,function(){return new $APP.V(null,1,5,$APP.W,[this.key],null)});$APP.Bc.prototype.va=Qf(6,function(){return this.first});$APP.Cc.prototype.va=Qf(5,function(){return null});$APP.V.prototype.va=Qf(4,function(){return 0<this.m?this.J(null,this.m-1):null});$APP.Md.prototype.va=Qf(3,function(){return this.N});$APP.E.prototype.Ta=Qf(2,function(){var a=this.V(null);return 0<a?new $APP.Xb(this,a-1,null):null});
$APP.V.prototype.Ta=Qf(1,function(){return 0<this.m?new $APP.Xb(this,this.m-1,null):null});$APP.Md.prototype.Ta=Qf(0,function(){return new $APP.E([this.N,this.key],0,null)});
var Bg=function Bg(a){switch(arguments.length){case 3:return Bg.j(arguments[0],arguments[1],arguments[2]);case 4:return Bg.D(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return Bg.$(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);case 6:return Bg.ua(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Bg.s(arguments[0],arguments[1],arguments[2],
arguments[3],arguments[4],arguments[5],new $APP.E(c.slice(6),0,null))}};Bg.j=function(a,b,c){var d=$APP.Z.j,e=$APP.kc.h(a,b);c=c.g?c.g(e):c.call(null,e);return d.call($APP.Z,a,b,c)};Bg.D=function(a,b,c,d){var e=$APP.Z.j,f=$APP.kc.h(a,b);c=c.h?c.h(f,d):c.call(null,f,d);return e.call($APP.Z,a,b,c)};Bg.$=function(a,b,c,d,e){var f=$APP.Z.j,h=$APP.kc.h(a,b);c=c.j?c.j(h,d,e):c.call(null,h,d,e);return f.call($APP.Z,a,b,c)};
Bg.ua=function(a,b,c,d,e,f){var h=$APP.Z.j,k=$APP.kc.h(a,b);c=c.D?c.D(k,d,e,f):c.call(null,k,d,e,f);return h.call($APP.Z,a,b,c)};Bg.s=function(a,b,c,d,e,f,h){return $APP.Z.j(a,b,$APP.Xc(c,$APP.kc.h(a,b),d,e,f,$APP.P([h])))};Bg.G=function(a){var b=$APP.G(a),c=$APP.J(a);a=$APP.G(c);var d=$APP.J(c);c=$APP.G(d);var e=$APP.J(d);d=$APP.G(e);var f=$APP.J(e);e=$APP.G(f);var h=$APP.J(f);f=$APP.G(h);h=$APP.J(h);return this.s(b,a,c,d,e,f,h)};Bg.I=6;
var cg=function cg(a,b){var d=a.exec(b);if(null==d)return null;var e=d[0],f=1===d.length?e:$APP.wd(d);return $APP.R(f,new $APP.Fc(null,function(){var h=e.length;h=d.index+(1>h?1:h);return h<=b.length?(h=b.substring(h),cg.h?cg.h(a,h):cg.call(null,a,h)):null},null))},hh=function hh(a){switch(arguments.length){case 0:return hh.B();case 1:return hh.g(arguments[0]);case 2:return hh.h(arguments[0],arguments[1]);case 3:return hh.j(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,
e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return hh.s(arguments[0],arguments[1],arguments[2],new $APP.E(c.slice(3),0,null))}};hh.B=function(){return $APP.xc};hh.g=function(a){return a};
hh.h=function(a,b){return function(){function c(l,m,n){l=b.j?b.j(l,m,n):b.call(null,l,m,n);return a.g?a.g(l):a.call(null,l)}function d(l,m){l=b.h?b.h(l,m):b.call(null,l,m);return a.g?a.g(l):a.call(null,l)}function e(l){l=b.g?b.g(l):b.call(null,l);return a.g?a.g(l):a.call(null,l)}function f(){var l=b.B?b.B():b.call(null);return a.g?a.g(l):a.call(null,l)}var h=null,k=function(){function l(n,p,t,v){var y=null;if(3<arguments.length){y=0;for(var A=Array(arguments.length-3);y<A.length;)A[y]=arguments[y+
3],++y;y=new $APP.E(A,0,null)}return m.call(this,n,p,t,y)}function m(n,p,t,v){n=$APP.Wc(b,n,p,t,v);return a.g?a.g(n):a.call(null,n)}l.I=3;l.G=function(n){var p=$APP.G(n);n=$APP.J(n);var t=$APP.G(n);n=$APP.J(n);var v=$APP.G(n);n=$APP.Gb(n);return m(p,t,v,n)};l.s=m;return l}();h=function(l,m,n,p){switch(arguments.length){case 0:return f.call(this);case 1:return e.call(this,l);case 2:return d.call(this,l,m);case 3:return c.call(this,l,m,n);default:var t=null;if(3<arguments.length){t=0;for(var v=Array(arguments.length-
3);t<v.length;)v[t]=arguments[t+3],++t;t=new $APP.E(v,0,null)}return k.s(l,m,n,t)}throw Error("Invalid arity: "+arguments.length);};h.I=3;h.G=k.G;h.B=f;h.g=e;h.h=d;h.j=c;h.s=k.s;return h}()};
hh.j=function(a,b,c){return function(){function d(m,n,p){m=c.j?c.j(m,n,p):c.call(null,m,n,p);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}function e(m,n){m=c.h?c.h(m,n):c.call(null,m,n);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}function f(m){m=c.g?c.g(m):c.call(null,m);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}function h(){var m=c.B?c.B():c.call(null);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}var k=null,l=function(){function m(p,
t,v,y){var A=null;if(3<arguments.length){A=0;for(var I=Array(arguments.length-3);A<I.length;)I[A]=arguments[A+3],++A;A=new $APP.E(I,0,null)}return n.call(this,p,t,v,A)}function n(p,t,v,y){p=$APP.Wc(c,p,t,v,y);p=b.g?b.g(p):b.call(null,p);return a.g?a.g(p):a.call(null,p)}m.I=3;m.G=function(p){var t=$APP.G(p);p=$APP.J(p);var v=$APP.G(p);p=$APP.J(p);var y=$APP.G(p);p=$APP.Gb(p);return n(t,v,y,p)};m.s=n;return m}();k=function(m,n,p,t){switch(arguments.length){case 0:return h.call(this);case 1:return f.call(this,
m);case 2:return e.call(this,m,n);case 3:return d.call(this,m,n,p);default:var v=null;if(3<arguments.length){v=0;for(var y=Array(arguments.length-3);v<y.length;)y[v]=arguments[v+3],++v;v=new $APP.E(y,0,null)}return l.s(m,n,p,v)}throw Error("Invalid arity: "+arguments.length);};k.I=3;k.G=l.G;k.B=h;k.g=f;k.h=e;k.j=d;k.s=l.s;return k}()};
hh.s=function(a,b,c,d){var e=fg($APP.R(a,$APP.R(b,$APP.R(c,d))));return function(){function f(k){var l=null;if(0<arguments.length){l=0;for(var m=Array(arguments.length-0);l<m.length;)m[l]=arguments[l+0],++l;l=new $APP.E(m,0,null)}return h.call(this,l)}function h(k){k=$APP.Tc($APP.G(e),k);for(var l=$APP.J(e);;)if(l){var m=$APP.G(l);k=m.g?m.g(k):m.call(null,k);l=$APP.J(l)}else return k}f.I=0;f.G=function(k){k=$APP.F(k);return h(k)};f.s=h;return f}()};
hh.G=function(a){var b=$APP.G(a),c=$APP.J(a);a=$APP.G(c);var d=$APP.J(c);c=$APP.G(d);d=$APP.J(d);return this.s(b,a,c,d)};hh.I=3;
var jg=function jg(a){switch(arguments.length){case 2:return jg.h(arguments[0],arguments[1]);case 3:return jg.j(arguments[0],arguments[1],arguments[2]);case 4:return jg.D(arguments[0],arguments[1],arguments[2],arguments[3]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return jg.s(arguments[0],arguments[1],arguments[2],arguments[3],new $APP.E(c.slice(4),0,null))}};
jg.h=function(a,b){if(a instanceof $APP.fd){var c=a.state;b=b.g?b.g(c):b.call(null,c);a=hg(a,b)}else a=$APP.kf(a,b);return a};jg.j=function(a,b,c){if(a instanceof $APP.fd){var d=a.state;b=b.h?b.h(d,c):b.call(null,d,c);a=hg(a,b)}else a=$APP.kf(a,b,c);return a};jg.D=function(a,b,c,d){if(a instanceof $APP.fd){var e=a.state;b=b.j?b.j(e,c,d):b.call(null,e,c,d);a=hg(a,b)}else a=$APP.kf(a,b,c,d);return a};
jg.s=function(a,b,c,d,e){return a instanceof $APP.fd?hg(a,$APP.Wc(b,a.state,c,d,e)):$APP.kf(a,b,c,d,e)};jg.G=function(a){var b=$APP.G(a),c=$APP.J(a);a=$APP.G(c);var d=$APP.J(c);c=$APP.G(d);var e=$APP.J(d);d=$APP.G(e);e=$APP.J(e);return this.s(b,a,c,d,e)};jg.I=4;var ig=null;lg.prototype.pb=function(){$APP.u(this.f)&&(this.value=this.f.B?this.f.B():this.f.call(null),this.f=null);return this.value};
lg.prototype.O=function(a,b,c){$APP.C(b,"#object[cljs.core.Delay ");$APP.X(new $APP.r(null,2,[$APP.yf,null==this.f?$APP.Jf:$APP.Cf,$APP.uf,this.value],null),b,c);return $APP.C(b,"]")};
var Dh=new $APP.T(null,"y2","y2",-718691301),di=new $APP.T(null,"y1","y1",589123466),Gh=new $APP.T(null,"translate","translate",1336199447),ah=new $APP.Cb("marooned.debug","insert-debug-panel","marooned.debug/insert-debug-panel",-785597226,null),Pg=new $APP.T(null,"transform","transform",1381301764),yh=new $APP.T(null,"y","y",-1757859776),xh=new $APP.T(null,"x","x",2099068185),Vg=new $APP.T(null,"r","r",-471384190),Vh=new $APP.T(null,"dur","dur",1464522452),mi=new $APP.T(null,"keyup","keyup",-794526927),
Th=new $APP.T(null,"attributeName","attributeName",-400177890),Wh=new $APP.T(null,"repeatCount","repeatCount",1447663848),fi=new $APP.T(null,"left-thruster-cone","left-thruster-cone",331882915),qh=new $APP.T(null,"h","h",1109658740),ci=new $APP.T(null,"x1","x1",-1863922247),rh=new $APP.T(null,"vh","vh",79552846),ei=new $APP.T(null,"x2","x2",-1362513475),Hg=new $APP.T(null,"debug-toggle","debug-toggle",292283581),sh=new $APP.T(null,"vs","vs",-2022097090),Bh=new $APP.T(null,"rotate","rotate",152705015),
Ug=new $APP.T(null,"cy","cy",755331060),Tg=new $APP.T(null,"cx","cx",1272694324),Ah=new $APP.T(null,"speed","speed",1257663751),Yg=new $APP.T(null,"points","points",-1486596883),kh=new $APP.T(null,"ts","ts",1617209904),nh=new $APP.T(null,"dh","dh",528137731),lh=new $APP.T(null,"dt","dt",-368444759),ni=new $APP.T(null,"mousedown","mousedown",1391242074),Fh=new $APP.T(null,"ship","ship",197863473),tg=new $APP.T(null,"display","display",242065432),hi=new $APP.T(null,"forward-thruster-cone","forward-thruster-cone",
-1370539011),Uh=new $APP.T(null,"values","values",372645556),Mh=new $APP.T(null,"scene","scene",1523800415),Yh=new $APP.T(null,"ry","ry",-334598563),Xh=new $APP.T(null,"rx","rx",1627208482),Oh=new $APP.T(null,"viewBox","viewBox",-469489477),gi=new $APP.T(null,"right-thruster-cone","right-thruster-cone",-1021778022),oi=new $APP.T(null,"keydown","keydown",-629268186),fh=new $APP.T(null,"debug?","debug?",-1831756173),bi=new $APP.T(null,"stroke-width","stroke-width",716836435),Ih=new $APP.T(null,"sound",
"sound",-2127407070),Eg=new $APP.T(null,"is-fullscreen?","is-fullscreen?",972486782),pi=new $APP.T(null,"mouseup","mouseup",350619456),Rh=new $APP.T(null,"fill","fill",883462889),Ph=new $APP.T(null,"scale","scale",-230427353),Nh=new $APP.Cb("marooned.scene","on-resize","marooned.scene/on-resize",-1898156757,null),Fg=new $APP.T(null,"can-fullscreen?","can-fullscreen?",-1592427507),ih=new $APP.Cb("marooned.debug","remove-debug-panel","marooned.debug/remove-debug-panel",1897953233,null),Eh=new $APP.T(null,
"hull","hull",-957096876),ai=new $APP.T(null,"stroke","stroke",1741823555),bh=new $APP.T(null,"id","id",-1388402092),ch=new $APP.T(null,"key","key",-1516042587),qi=new $APP.T(null,"resize","resize",297367086),Ig=new $APP.T(null,"reset!","reset!",-1113255895);var Mg=new $APP.V(null,4,5,$APP.W,[Gh,Bh,Ph,new $APP.T(null,"skew","skew",-595121815)],null),ri=$APP.De(Mg),si=$APP.gd.h(ri,Pg),zh=function zh(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return zh.s(arguments[0],1<c.length?new $APP.E(c.slice(1),0,null):null)};
zh.s=function(a,b){if($APP.F(b)){a:{var c=$APP.F(b);$APP.G(c);c=$APP.J(c);$APP.G(c);$APP.J(c);c=$APP.vd;for(var d=b;;){b=c;d=$APP.F(d);c=$APP.G(d);d=$APP.J(d);var e=$APP.G(d),f=$APP.J(d);d=e;e=f;if($APP.ua(c))break a;f=si.g?si.g(c):si.call(null,c);$APP.u(f)||a.setAttributeNS(null,$APP.Ee(c),$APP.z.g(d));b=$APP.u(f)?$APP.gd.h(b,new $APP.V(null,2,5,$APP.W,[c,d],null)):b;d=e;c=b}}if($APP.F(b)){b=Qg(a,b);c=$APP.F(ri);d=null;for(f=e=0;;)if(f<e){var h=d.J(null,f),k=h.g?h.g(b):h.call(null,b);a[h]=k;f+=1}else if(c=
$APP.F(c))$APP.hc(c)?(e=$APP.mb(c),c=$APP.nb(c),d=e,e=$APP.K(e)):(d=$APP.G(c),e=d.g?d.g(b):d.call(null,b),a[d]=e,c=$APP.J(c),d=null,e=0),f=0;else break;a.setAttributeNS(null,"transform",Ng(b))}}return a};zh.I=1;zh.G=function(a){var b=$APP.G(a);a=$APP.J(a);return this.s(b,a)};var ag=function ag(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return ag.s(arguments[0],1<c.length?new $APP.E(c.slice(1),0,null):null)};
ag.s=function(a,b){a=document.createElementNS("http://www.w3.org/2000/svg",a);var c=$APP.ec($APP.G(b))?new $APP.V(null,2,5,$APP.W,[$APP.G(b),$APP.Gb(b)],null):new $APP.V(null,2,5,$APP.W,[null,b],null);b=$APP.Q(c,0,null);c=$APP.Q(c,1,null);a.translate=new $APP.V(null,2,5,$APP.W,[0,0],null);a.rotate=0;a.scale=1;b=$APP.Tc($APP.of,$APP.Uc($APP.Y,$APP.xc,$APP.P([b])));$APP.Uc(zh,a,b);b=$APP.F(c);c=null;for(var d=0,e=0;;)if(e<d){var f=c.J(null,e);$APP.dc(f)?Rg(a,f):Rg(a,$APP.P([f]));e+=1}else if(b=$APP.F(b))c=
b,$APP.hc(c)?(b=$APP.mb(c),e=$APP.nb(c),c=b,d=$APP.K(b),b=e):(b=$APP.G(c),$APP.dc(b)?Rg(a,b):Rg(a,$APP.P([b])),b=$APP.J(c),c=null,d=0),e=0;else break;return a};ag.I=1;ag.G=function(a){var b=$APP.G(a);a=$APP.J(a);return this.s(b,a)};var Zh=bg("g"),Sh=bg("animate");var dh=new $APP.V(null,10,5,$APP.W,[new $APP.V(null,2,5,$APP.W,[lh,Zg],null),new $APP.V(null,2,5,$APP.W,[xh,Zg],null),new $APP.V(null,2,5,$APP.W,[yh,Zg],null),new $APP.V(null,2,5,$APP.W,[rh,Zg],null),new $APP.V(null,2,5,$APP.W,[sh,Zg],null),new $APP.V(null,2,5,$APP.W,[qh,Zg],null),new $APP.V(null,2,5,$APP.W,[nh,Zg],null),new $APP.V(null,2,5,$APP.W,[$APP.Kf,$g],null),new $APP.V(null,2,5,$APP.W,[$APP.If,$g],null),new $APP.V(null,2,5,$APP.W,[$APP.Hf,$g],null)],null);var Ch=Math.PI,th=Math.sin,uh=Math.cos,vh=Math.atan2,wh=Math.sqrt,ph=Ch/1E3,oh=-ph,mh=ph/80,Kh=new $APP.r(null,7,[kh,0,xh,0,yh,0,rh,0,sh,0,qh,0,nh,0],null);var ji=new lg(function(){gg($APP.P(["init: registering worker..."]));$APP.$e(navigator,"serviceWorker").register("worker.js",{scope:"./"}).then(function(){return gg($APP.P(["init: worker registered"]))}).catch(function(b){return gg($APP.P(["init: worker failed",b]))});gg($APP.P(["init: init modules"]));Cg();Gg();yg(window,oi,Jg(!0));yg(window,mi,Jg(!1));yg("left-thruster",ni,Kg($APP.Kf,!0));yg("left-thruster",pi,Kg($APP.Kf,!1));yg("right-thruster",ni,Kg($APP.If,!0));yg("right-thruster",pi,Kg($APP.If,
!1));yg("forward-thruster",ni,Kg($APP.Hf,!0));yg("forward-thruster",pi,Kg($APP.Hf,!1));yg("cannon",ni,Kg($APP.Ff,!0));yg("cannon",pi,Kg($APP.Ff,!1));gg($APP.P(["init: game init"]));Lh();gg($APP.P(["init: scene"]));yg(window,qi,Qh);ii();gg($APP.P(["init: debug"]));jh();gg($APP.P(["init: animation"]));var a=$APP.$e(window,"performance").now();window.requestAnimationFrame(function d(c){jg.j($APP.Lf,Hh,c-a);return window.requestAnimationFrame(d)});return gg($APP.P(["init: done"]))}),ti=["marooned","app",
"run"],ui=$APP.df;ti[0]in ui||"undefined"==typeof ui.execScript||ui.execScript("var "+ti[0]);for(var vi;ti.length&&(vi=ti.shift());)ti.length||void 0===ki?ui=ui[vi]&&ui[vi]!==Object.prototype[vi]?ui[vi]:ui[vi]={}:ui[vi]=ki;
}).call(this);