(function(){
'use strict';var ng=function(a,b){return $APP.aa[a]=b},og=function(a,b){var c=Array(a.length-2);$APP.lc(a,0,c,0,2*b);$APP.lc(a,2*(b+1),c,2*b,c.length-2*b);return c},pg=function(a){return null==a},qg=function(a,b){if(null!=a&&null!=a.jb)a=a.jb(a,b);else{var c=qg[$APP.q(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=qg._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $APP.x("IMap.-dissoc",a);}return a},rg=function(a){if(null!=a&&null!=a.xa)a=a.xa(a);else{var b=rg[$APP.q(null==
a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=rg._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.x("IStack.-peek",a);}return a},sg=function(a){if(null!=a&&null!=a.ya)a=a.ya(a);else{var b=sg[$APP.q(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=sg._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.x("IStack.-pop",a);}return a},tg=function(){},ug=function(a){if(null!=a&&null!=a.Wa)a=a.Wa(a);else{var b=ug[$APP.q(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,
a);else if(b=ug._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.x("IReversible.-rseq",a);}return a},vg=function(a,b){if(null!=a&&null!=a.Vb)a=a.Vb(a,b);else{var c=vg[$APP.q(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=vg._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $APP.x("IReset.-reset!",a);}return a},wg=function(a){if(null==$APP.ra)throw Error("No *print-fn* fn set for evaluation environment");$APP.ra.call(null,a)},xg=function(a){var b=new $APP.T(null,3,5,
$APP.V,[3E3,3100,3200],null);return $APP.kb($APP.tc(function(c,d){d=a.g?a.g(d):a.call(null,d);return $APP.jb(c,d)},$APP.ib($APP.yd),b))},yg=function(){var a=$APP.I(new $APP.T(null,3,5,$APP.V,[3E3,3100,3200],null));return 0>=a?$APP.G:$APP.nc(0)&&$APP.nc(a)&&$APP.nc(1)?new $APP.Ke(null,0,a,1,null,null,null):new $APP.Le(null,0,a,1,null,null,null)},zg=function(a){return function(){function b(h,k){return $APP.va(a.h?a.h(h,k):a.call(null,h,k))}function c(h){return $APP.va(a.g?a.g(h):a.call(null,h))}function d(){return $APP.va(a.C?
a.C():a.call(null))}var e=null,f=function(){function h(l,m,n){var p=null;if(2<arguments.length){p=0;for(var t=Array(arguments.length-2);p<t.length;)t[p]=arguments[p+2],++p;p=new $APP.C(t,0,null)}return k.call(this,l,m,p)}function k(l,m,n){return $APP.va($APP.Yc(a,l,m,n))}h.H=2;h.F=function(l){var m=$APP.F(l);l=$APP.H(l);var n=$APP.F(l);l=$APP.Ib(l);return k(m,n,l)};h.m=k;return h}();e=function(h,k,l){switch(arguments.length){case 0:return d.call(this);case 1:return c.call(this,h);case 2:return b.call(this,
h,k);default:var m=null;if(2<arguments.length){m=0;for(var n=Array(arguments.length-2);m<n.length;)n[m]=arguments[m+2],++m;m=new $APP.C(n,0,null)}return f.m(h,k,m)}throw Error("Invalid arity: "+arguments.length);};e.H=2;e.F=f.F;e.C=d;e.g=c;e.h=b;e.m=f.m;return e}()},Ag=function(a,b){return function(){function c(l,m,n){return a.B?a.B(b,l,m,n):a.call(null,b,l,m,n)}function d(l,m){return a.j?a.j(b,l,m):a.call(null,b,l,m)}function e(l){return a.h?a.h(b,l):a.call(null,b,l)}function f(){return a.g?a.g(b):
a.call(null,b)}var h=null,k=function(){function l(n,p,t,v){var A=null;if(3<arguments.length){A=0;for(var D=Array(arguments.length-3);A<D.length;)D[A]=arguments[A+3],++A;A=new $APP.C(D,0,null)}return m.call(this,n,p,t,A)}function m(n,p,t,v){return $APP.$c(a,b,n,p,t,$APP.O([v]))}l.H=3;l.F=function(n){var p=$APP.F(n);n=$APP.H(n);var t=$APP.F(n);n=$APP.H(n);var v=$APP.F(n);n=$APP.Ib(n);return m(p,t,v,n)};l.m=m;return l}();h=function(l,m,n,p){switch(arguments.length){case 0:return f.call(this);case 1:return e.call(this,
l);case 2:return d.call(this,l,m);case 3:return c.call(this,l,m,n);default:var t=null;if(3<arguments.length){t=0;for(var v=Array(arguments.length-3);t<v.length;)v[t]=arguments[t+3],++t;t=new $APP.C(v,0,null)}return k.m(l,m,n,t)}throw Error("Invalid arity: "+arguments.length);};h.H=3;h.F=k.F;h.C=f;h.g=e;h.h=d;h.j=c;h.m=k.m;return h}()},Cg=function(a){var b=/([a-z]+)\(([^)]+)\)\s*/;if("string"===typeof a)return Bg(b,a);throw new TypeError("re-seq must match against a string.");},Dg=function(a,b){return new $APP.Ic(null,
function(){var c=$APP.E(b);if(c){if($APP.kc(c)){for(var d=$APP.nb(c),e=$APP.I(d),f=new $APP.Kc(Array(e)),h=0;;)if(h<e){var k=$APP.ac(d,h);k=a.g?a.g(k):a.call(null,k);$APP.u(k)&&(k=$APP.ac(d,h),f.add(k));h+=1}else break;return $APP.Nc(f.O(),Dg(a,$APP.ob(c)))}d=$APP.F(c);c=$APP.Ib(c);return $APP.u(a.g?a.g(d):a.call(null,d))?$APP.R(d,Dg(a,c)):Dg(a,c)}return null},null)},Eg=function(a,b){return Dg(zg(a),b)},Fg=function(a){return(null!=a?a.o&134217728||$APP.B===a.rc||(a.o?0:$APP.w(tg,a)):$APP.w(tg,a))?
(a=ug(a))?a:$APP.G:$APP.tc($APP.jd,$APP.G,a)},Gg=function(a){var b=$APP.Y.j($APP.pa(),$APP.la,!1);wg($APP.$e(a,b));$APP.u($APP.qa)?(a=$APP.pa(),wg("\n"),a=($APP.Q.h(a,$APP.ka),null)):a=null;return a},Hg=function(a,b){if(a instanceof $APP.id){var c=a.fc;if(null!=c&&!$APP.u(c.g?c.g(b):c.call(null,b)))throw Error("Validator rejected reference state");c=a.state;a.state=b;if(null!=a.Ib)a:for(var d=$APP.E(a.Ib),e=null,f=0,h=0;;)if(h<f){var k=e.J(null,h),l=$APP.P(k,0,null);k=$APP.P(k,1,null);k.B?k.B(l,a,
c,b):k.call(null,l,a,c,b);h+=1}else if(d=$APP.E(d))$APP.kc(d)?(e=$APP.nb(d),d=$APP.ob(d),l=e,f=$APP.I(e),e=l):(e=$APP.F(d),l=$APP.P(e,0,null),k=$APP.P(e,1,null),k.B?k.B(l,a,c,b):k.call(null,l,a,c,b),d=$APP.H(d),e=null,f=0),h=0;else break a;return b}return vg(a,b)},Ig=function(a){this.f=a;this.value=null;this.o=2147516416;this.D=1},Jg=function(a){if("string"===typeof a)return $APP.Me(/[\x00-\x20]*[+-]?NaN[\x00-\x20]*/,a)?NaN:$APP.Me(/[\x00-\x20]*[+-]?(Infinity|((\d+\.?\d*|\.\d+)([eE][+-]?\d+)?)[dDfF]?)[\x00-\x20]*/,
a)?parseFloat(a):null;throw Error(["Expected string, got: ",$APP.y.g(null==a?"nil":$APP.q(a))].join(""));},Kg=function(a){return $APP.u(a)?$APP.ia(a,"classList"):null},Lg=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;a:{c=arguments[0];d=arguments[1];var e=arguments[2];for(b=3<b.length?new $APP.C(b.slice(3),0,null):null;;)if(c[d]=e,$APP.E(b))d=$APP.F(b),e=$APP.F($APP.H(b)),b=$APP.H($APP.H(b));else break a}},Mg=function(a,b){var c=$APP.P(a,0,null);a=$APP.P(a,
1,null);var d=$APP.P(b,0,null);b=$APP.P(b,1,null);var e=a-c,f=b-d;return function(h){return d+(h-c)/e*f}},Ng=function(a,b){return function(c){return c<a?a:c>b?b:c}},Og=function(a,b,c){var d=$APP.ed(c);c=$APP.Q.h(d,$APP.Hf);d=$APP.Q.h(d,$APP.Gf);a=c-a;b-=d;return $APP.ig.h?$APP.ig.h(a,b):$APP.ig.call(null,a,b)},Pg=function(a,b,c){var d=$APP.ed(c);c=$APP.Q.h(d,$APP.Hf);d=$APP.Q.h(d,$APP.Gf);a=c-a;b=d-b;b=a*a+b*b;return $APP.jg.g?$APP.jg.g(b):$APP.jg.call(null,b)},Qg=function(a,b,c){a=$APP.ed(a);var d=
$APP.Q.h(a,$APP.Pf),e=$APP.Q.h(a,$APP.If);a=e*($APP.gg.g?$APP.gg.g(d):$APP.gg.call(null,d))+c*($APP.gg.g?$APP.gg.g(b):$APP.gg.call(null,b));b=e*($APP.hg.g?$APP.hg.g(d):$APP.hg.call(null,d))+c*($APP.hg.g?$APP.hg.g(b):$APP.hg.call(null,b));c=$APP.ig.h?$APP.ig.h(a,b):$APP.ig.call(null,a,b);d=a*a+b*b;d=$APP.jg.g?$APP.jg.g(d):$APP.jg.call(null,d);return new $APP.r(null,4,[$APP.Pf,c,$APP.If,d,$APP.Nf,a,$APP.Mf,-b],null)},Rg=function(a){return"string"===typeof a?document.getElementById(a):a},Sg=function(a,
b){a=Kg(Rg(a));b=$APP.E(b);for(var c=null,d=0,e=0;;)if(e<d){var f=c.J(null,e);a.add(f);e+=1}else if(b=$APP.E(b))c=b,$APP.kc(c)?(b=$APP.nb(c),e=$APP.ob(c),c=b,d=$APP.I(b),b=e):(b=$APP.F(c),a.add(b),b=$APP.H(c),c=null,d=0),e=0;else break},Ug=function(){var a=$APP.O([Tg,"display: none;"]),b=Rg("fullscreen"),c=$APP.E(a);$APP.F(c);c=$APP.H(c);$APP.F(c);for($APP.H(c);;){c=$APP.E(a);a=$APP.F(c);c=$APP.H(c);var d=$APP.F(c);c=$APP.H(c);b.setAttribute($APP.He(a),$APP.y.g(d));if($APP.E(c))a=c;else break}},Vg=
function(a,b){a=Rg(a);Lg(a,"textContent",b);return a},Wg=function(a,b){a=Rg(a);b=$APP.E(b);for(var c=null,d=0,e=0;;)if(e<d){var f=c.J(null,e);a.append(f);e+=1}else if(b=$APP.E(b))c=b,$APP.kc(c)?(b=$APP.nb(c),e=$APP.ob(c),c=b,d=$APP.I(b),b=e):(b=$APP.F(c),a.append(b),b=$APP.H(c),c=null,d=0),e=0;else break},Xg=function(a,b){b=$APP.hc($APP.F(b))?new $APP.T(null,2,5,$APP.V,[$APP.F(b),$APP.Ib(b)],null):new $APP.T(null,2,5,$APP.V,[null,b],null);var c=$APP.P(b,0,null);b=$APP.P(b,1,null);a=document.createElement(a);
c=$APP.E(c);for(var d=null,e=0,f=0;;)if(f<e){var h=d.J(null,f),k=$APP.P(h,0,null);h=$APP.P(h,1,null);$APP.J.h(k,$APP.Sf)?Sg(a,$APP.X.h($APP.y,$APP.gc(h)?Eg(pg,h):$APP.R(h,null))):a.setAttribute($APP.He(k),$APP.y.g(h));f+=1}else if(c=$APP.E(c))$APP.kc(c)?(e=$APP.nb(c),c=$APP.ob(c),d=e,e=$APP.I(e)):(e=$APP.F(c),d=$APP.P(e,0,null),e=$APP.P(e,1,null),$APP.J.h(d,$APP.Sf)?Sg(a,$APP.X.h($APP.y,$APP.gc(e)?Eg(pg,e):$APP.R(e,null))):a.setAttribute($APP.He(d),$APP.y.g(e)),c=$APP.H(c),d=null,e=0),f=0;else break;
b=$APP.E(b);c=null;for(e=d=0;;)if(e<d)f=c.J(null,e),$APP.gc(f)?Wg(a,f):Wg(a,$APP.O([f])),e+=1;else if(b=$APP.E(b))c=b,$APP.kc(c)?(b=$APP.nb(c),e=$APP.ob(c),c=b,d=$APP.I(b),b=e):(b=$APP.F(c),$APP.gc(b)?Wg(a,b):Wg(a,$APP.O([b])),b=$APP.H(c),c=null,d=0),e=0;else break;return a},Yg=function(a){a=Rg(a);$APP.u(a)&&a.remove()},Zg=function(a,b,c,d){a=Rg(a);a.addEventListener($APP.He(b),c,$APP.Cf(d));return a},$g=function(a,b,c){return Zg(a,b,c,null)},ah=function(a,b){return Z.B(a,$APP.Kf,$APP.Af,new $APP.r(null,
3,[$APP.Kf,$APP.cg,$APP.Yf,b,$APP.Uf,$APP.Uf.g(a)],null))},bh=function(a){var b=$APP.ed(null),c=$APP.Q.h(b,$APP.Vf);b=$APP.Q.h(b,$APP.ag);$APP.u(c)&&a.stereo(c);$APP.u(b)&&a.volume(b);return a.play()},ch=function(a,b){b=$APP.Q.h($APP.mg,b);bh(b);return a},dh=function(a,b,c){var d=$APP.ed(c);c=$APP.Q.h(d,$APP.Vf);d=$APP.Q.h(d,$APP.ag);var e=$APP.Q.h($APP.mg,b);var f=$APP.Xf.g(a);f=b.g?b.g(f):b.call(null,f);f=$APP.u(f)?f:bh(e);$APP.u(c)&&e.stereo(c);$APP.u(d)&&e.volume(d);return Z.R(a,$APP.Xf,$APP.Y,
b,f)},fh=function(a,b,c){var d=$APP.Q.h($APP.mg,b);var e=$APP.Xf.g(a);e=b.g?b.g(e):b.call(null,e);return $APP.u(e)?($APP.u(c)?d.fade(d.volume(),0,c,e):d.stop(e),Z.B(a,$APP.Xf,eh,b)):a},hh=function(){return gh.B($APP.dg,Z,$APP.Ff,function(a){(a=$APP.va(a))?Kg(Rg("sound")).add("active"):Kg(Rg("sound")).remove("active");$APP.kg.Howler.mute(!a);return a})},ih=function(a){if($APP.u(a))return Kg(Rg("fullscreen")).remove("active"),document.exitFullscreen().then(function(){return Gg($APP.O(["fullscreen: success"]))},
function(){return Gg($APP.O(["fullscreen: rejected"]))}),!0;Kg(Rg("fullscreen")).add("active");Rg("wrapper").requestFullscreen().then(function(){return Gg($APP.O(["fullscreen: success"]))},function(){return Gg($APP.O(["fullscreen: rejected"]))});return!1},lh=function(a){var b=document.fullscreenEnabled,c=null!=document.fullscreenElement;$APP.u(b)||Ug();$APP.u(b)&&$g("fullscreen",$APP.Qf,function(){return gh.B($APP.dg,Z,jh,ih)});return $APP.Y.m(a,kh,b,$APP.O([jh,c]))},mh=function(a){return $APP.u(a)?
a.toFixed(2):"-"},nh=function(a){return $APP.u(a)?"ON":"OFF"},qh=function(){Wg("wrapper",$APP.O([Xg("div",$APP.O([new $APP.r(null,1,[oh,"debug"],null),Xg("table",$APP.O([Xg("tbody",$APP.O([function(){return function c(b){return new $APP.Ic(null,function(){for(;;){var d=$APP.E(b);if(d){if($APP.kc(d)){var e=$APP.nb(d),f=$APP.I(e),h=new $APP.Kc(Array(f));a:for(var k=0;;)if(k<f){var l=$APP.ac(e,k);l=$APP.P(l,0,null);l=Xg("tr",$APP.O([Xg("td",$APP.O([l])),Xg("td",$APP.O([new $APP.r(null,1,[oh,["debug-data-",
$APP.y.g(l)].join("")],null),"-"]))]));h.add(l);k+=1}else{e=!0;break a}return e?$APP.Nc(h.O(),c($APP.ob(d))):$APP.Nc(h.O(),null)}h=$APP.F(d);h=$APP.P(h,0,null);return $APP.R(Xg("tr",$APP.O([Xg("td",$APP.O([h])),Xg("td",$APP.O([new $APP.r(null,1,[oh,["debug-data-",$APP.y.g(h)].join("")],null),"-"]))])),c($APP.Ib(d)))}return null}},null)}(ph)}()]))]))]))]))},sh=function(){return gh.B($APP.dg,Z,rh,function(a){if($APP.u(a)){a=Rg("wrapper");var b=Rg("debug");$APP.u($APP.u(a)?b:a)&&a.removeChild(b);return!1}qh();
return!0})},th=function(a){if($APP.u(rh.g(a)))for(var b=$APP.E(ph),c=null,d=0,e=0;;)if(e<d){var f=c.J(null,e),h=$APP.P(f,0,null),k=$APP.P(f,1,null),l=Rg(["debug-data-",$APP.y.g(h)].join(""));if($APP.u(l)){var m=l;Vg(m,$APP.tc(function(){return function(t,v){return v.g?v.g(t):v.call(null,t)}}(b,c,d,e,m,l,f,h,k),a,k))}e+=1}else if(h=$APP.E(b)){f=h;if($APP.kc(f))b=$APP.nb(f),e=$APP.ob(f),c=b,d=$APP.I(b),b=e;else{k=$APP.F(f);l=$APP.P(k,0,null);m=$APP.P(k,1,null);var n=Rg(["debug-data-",$APP.y.g(l)].join(""));
if($APP.u(n)){var p=n;Vg(p,$APP.tc(function(){return function(t,v){return v.g?v.g(t):v.call(null,t)}}(b,c,d,e,p,n,k,l,m,f,h),a,m))}b=$APP.H(f);c=null;d=0}e=0}else break;return a},wh=function(a){return function(b){return gh.h($APP.dg,function(c){return Z.m(c,uh,Z,a,$APP.Y,vh,$APP.O([b,$APP.Uf,$APP.Uf.g(c)]))})}},yh=function(a){return function(b){if(!$APP.u(function(){var d=b.repeat;if($APP.u(d))return d;d=b.ctrlKey;return $APP.u(d)?d:b.metaKey}())){var c=function(){var d=b.code;return xh.g?xh.g(d):
xh.call(null,d)}();$APP.u(c)&&(b.preventDefault(),c.g?c.g(a):c.call(null,a))}return null}},zh=function(a,b){return function(c){c.preventDefault();gh.h($APP.dg,function(d){return Z.m(d,uh,Z,a,$APP.Y,vh,$APP.O([b,$APP.Uf,$APP.Uf.g(d)]))});return null}},Fh=function(a){$g($g($g($g($g(Rg($APP.He(a)),Ah,zh(a,!0)),Bh,zh(a,!1)),Ch,zh(a,!0)),Dh,zh(a,!1)),Eh,zh(a,!1))},Ih=function(a){$g($g(window,Gh,yh(!0)),Hh,yh(!1));Fh($APP.Ef);Fh($APP.Lf);Fh($APP.Wf);Fh($APP.$f);$g("sound",$APP.Qf,function(){return hh()});
return a},Jh=function(a){return $APP.u(a)?$APP.tc(function(b,c){$APP.P(c,0,null);var d=$APP.P(c,1,null),e=$APP.P(c,2,null);c=$APP.Y.j;d=$APP.Ve.g(d);var f=$APP.X.h,h=/[\s,]/;e="/(?:)/"===$APP.y.g(h)?$APP.jd.h($APP.zd($APP.R("",$APP.X.h($APP.y,$APP.E(e)))),""):$APP.zd($APP.y.g(e).split(h));if(1<$APP.I(e))a:for(;;)if(""===(null==e?null:rg(e)))e=null==e?null:sg(e);else break a;return c.call($APP.Y,b,d,f.call($APP.X,Jg,e))},$APP.dd,Cg(a)):null},Lh=function(a){return $APP.tc(function(b,c){var d=c.g?c.g(a):
c.call(null,a);if($APP.u(d)){b=$APP.y.g(b);c=$APP.He(c);var e=$APP.y,f=e.g;if($APP.gc(d))a:{var h=new $APP.ja;for(d=$APP.E(d);;)if(null!=d)h.append($APP.y.g($APP.F(d))),d=$APP.H(d),null!=d&&h.append(" ");else{d=h.toString();break a}}b=[b,c,"(",f.call(e,d),") "].join("")}return b},"",Kh)},Mh=function(a){return $APP.tc(function(b,c){var d=$APP.ia(a,c);return $APP.u(d)?$APP.Y.j(b,c,d):b},$APP.dd,Kh)},Oh=function(a,b){return $APP.tc(function(c,d){var e=$APP.P(d,0,null);d=$APP.P(d,1,null);return $APP.J.h(e,
Nh)?Jh(d):$APP.Y.j(c,e,d)},Mh(a),b)},Qh=function(a,b){b=Oh(a,b);for(var c=$APP.E(Ph),d=null,e=0,f=0;;)if(f<e){var h=d.J(null,f),k=h.g?h.g(b):h.call(null,b);a[h]=k;f+=1}else if(c=$APP.E(c))$APP.kc(c)?(e=$APP.nb(c),c=$APP.ob(c),d=e,e=$APP.I(e)):(d=$APP.F(c),e=d.g?d.g(b):d.call(null,b),a[d]=e,c=$APP.H(c),d=null,e=0),f=0;else break;a.setAttribute("transform",Lh(b))},Rh=function(a,b){a=Rg(a);b=$APP.E(b);for(var c=null,d=0,e=0;;)if(e<d){var f=c.J(null,e);a.append(f);e+=1}else if(b=$APP.E(b))c=b,$APP.kc(c)?
(b=$APP.nb(c),e=$APP.ob(c),c=b,d=$APP.I(b),b=e):(b=$APP.F(c),a.append(b),b=$APP.H(c),c=null,d=0),e=0;else break;return a},Sh=function(a,b){var c=document.createElementNS("http://www.w3.org/2000/svg","text");a=$APP.E(a);for(var d=null,e=0,f=0;;)if(f<e){var h=d.J(null,f),k=$APP.P(h,0,null);h=$APP.P(h,1,null);c.setAttribute($APP.He(k),$APP.y.g(h));f+=1}else if(a=$APP.E(a))$APP.kc(a)?(e=$APP.nb(a),a=$APP.ob(a),d=e,e=$APP.I(e)):(e=$APP.F(a),d=$APP.P(e,0,null),e=$APP.P(e,1,null),c.setAttribute($APP.He(d),
$APP.y.g(e)),a=$APP.H(a),d=null,e=0),f=0;else break;return Rh(c,b)},Vh=function(a){return Z.j(a,Th,function(b){Vg(Uh.g(b),"");Vg($APP.Jf.g(b),"");return $APP.Y.j(b,Th,$APP.G)})},fi=function(a,b,c,d,e,f,h){var k=Wh(new $APP.r(null,3,[Xh,c,Yh,d,Zh,4],null));c=new $APP.r(null,5,[$h,k,ai,bi.h?bi.h(c,d):bi.call(null,c,d),$APP.Pf,e,ci,f,di,h],null);d=Th.g(a);b=b.g?b.g(d):b.call(null,d);Rh(b,$APP.O([k]));return ei.B(a,new $APP.T(null,2,5,$APP.V,[Th,Th],null),$APP.jd,c)},gi=function(a,b){Yg($h.g(b));return ei.j(a,
new $APP.T(null,2,5,$APP.V,[Th,Th],null),function(c){return Eg(function(d){return d===b},c)})},li=function(a){var b=hi.g(ii.g(a));return $APP.tc(function(c,d){var e=$APP.Pf.g(d),f=ai.g(d),h=f.x+10*($APP.gg.g?$APP.gg.g(e):$APP.gg.call(null,e)),k=f.y+-10*($APP.hg.g?$APP.hg.g(e):$APP.hg.call(null,e)),l=ci.g(d);e=di.g(d);f.x=h;f.y=k;if($APP.va(ji.h(b,f)))return gi(c,d);if($APP.u(l.g?l.g(f):l.call(null,f)))return c=gi(c,d),e.g?e.g(c):e.call(null,c);ki.m($h.g(d),$APP.O([Xh,h,Yh,k]));return c},a,Th.g(Th.g(a)))},
pi=function(a){var b=$APP.ed(a);a=$APP.Q.h(b,$APP.Hf);b=$APP.Q.h(b,$APP.Gf);return mi(new $APP.r(null,1,[ni,new $APP.T(null,2,5,$APP.V,[a,b],null)],null),Wh(new $APP.r(null,2,[Zh,350,oi,"url(#blackhole-glow)"],null)),Wh(new $APP.r(null,2,[Zh,30,oi,"black"],null)))},Ai=function(a,b,c){return mi(new $APP.r(null,3,[ni,new $APP.T(null,2,5,$APP.V,[a,b],null),qi,c,ri,"none"],null),si(new $APP.r(null,5,[oi,"yellow",Xh,0,Yh,0,ti,3,ui,3],null),vi(new $APP.r(null,4,[wi,"ry",xi,"3;6;3",yi,"100ms",zi,"indefinite"],
null)),vi(new $APP.r(null,4,[wi,"fill-opacity",xi,"0.5;1.0;0.5",yi,"100ms",zi,"indefinite"],null))))},Ci=function(a,b,c){var d=ki.m;var e=Bi.g(Uh.g(a));e=b.g?b.g(e):b.call(null,e);d.call(ki,e,$APP.O(["display",$APP.u(c)?"on":"none"]));return $APP.u(c)?dh(a,b,null):fh(a,b,100)},Di=function(a){return $APP.tc(function(b,c){return Ci(b,c,!1)},a,new $APP.T(null,3,5,$APP.V,[$APP.Ef,$APP.Lf,$APP.Wf],null))},Ki=function(a){var b=$APP.Hf.g(Uh.g(a)),c=$APP.hd(function(e){var f=$APP.P(e,0,null);e=$APP.P(e,1,
null);return b>f?e:null},Ei),d=$APP.P(c,0,null);c=$APP.P(c,1,null);return Z.B(Di(a),Uh,$APP.Af,new $APP.r(null,7,[$APP.Hf,d,$APP.Gf,c,Fi,0,Gi,0,Hi,0,Ii,0,Ji,$APP.yd],null))},Mi=function(a,b,c){var d=$APP.gg.g?$APP.gg.g(c):$APP.gg.call(null,c),e=$APP.hg.g?$APP.hg.g(c):$APP.hg.call(null,c);return $APP.X.h(function(f){var h=$APP.P(f,0,null),k=$APP.P(f,1,null);f=a-(h*e+k*d);h=b+(k*e-h*d);return bi.h?bi.h(f,h):bi.call(null,f,h)},Li)},Qi=function(a){var b=$APP.Uf.g(a),c=$APP.$f.g(uh.g(a)),d=function(){var f=
vh.g(c);return $APP.u(f)?$APP.J.h($APP.Uf.g(c),b):f}(),e=Ni.g($APP.Jf.g(a));return $APP.u(d)?(d=Uh.g(a),2E3>b-Ii.g(d)?ch(a,$APP.Qf):Oi(fi(ch(a,$APP.$f),Uh,$APP.Hf.g(d),$APP.Gf.g(d),$APP.Pf.g(d),function(f){return ji.h(e,f)},function(f){return Z.R(f,$APP.Jf,$APP.Y,Pi,!0)}),new $APP.T(null,2,5,$APP.V,[Uh,Ii],null),b)):a},Ti=function(){var a=Rg("wrapper"),b=a.clientWidth;a=a.clientHeight;var c=b/2E3;var d=a/1E3;c=c<d?c:d;ki.m("game",$APP.O([Ri,["0 0 ",$APP.y.g(b)," ",$APP.y.g(a)].join("")]));return ki.m("scene",
$APP.O([Si,c,ni,new $APP.T(null,2,5,$APP.V,[0,(a-1E3*c)/2],null)]))},Vi=function(a){var b=Uh.g(a),c=$APP.Jf.g(a),d=$APP.Hf.g(c),e=$APP.Gf.g(c);c=function(){var h=$APP.Hf.g(b)-d,k=e-$APP.Gf.g(b);return $APP.ig.h?$APP.ig.h(h,k):$APP.ig.call(null,h,k)}();var f=Ni.g(b);return fi(a,$APP.Jf,d,e,c,function(h){return ji.h(f,h)},function(h){return ah(ch(h,$APP.Rf),Ui)})},ij=function(a){var b=Wi(new $APP.r(null,3,[Xi,2,oi,"rgb(209, 209, 89)",Yi,$APP.X.h(function(d){var e=$APP.P(d,0,null);d=$APP.P(d,1,null);
return new $APP.T(null,2,5,$APP.V,[2350+e,470+d],null)},new $APP.T(null,4,5,$APP.V,[new $APP.T(null,2,5,$APP.V,[-30,0],null),new $APP.T(null,2,5,$APP.V,[0,-40],null),new $APP.T(null,2,5,$APP.V,[30,0],null),new $APP.T(null,2,5,$APP.V,[0,40],null)],null))],null)),c=mi(new $APP.r(null,3,[Xi,2,Zi,"yellow",oi,"none"],null),b,$i(new $APP.r(null,2,[ni,new $APP.T(null,2,5,$APP.V,[2350,470],null),Yi,new $APP.T(null,3,5,$APP.V,[new $APP.T(null,2,5,$APP.V,[-30,0],null),new $APP.T(null,2,5,$APP.V,[0,10],null),
new $APP.T(null,2,5,$APP.V,[30,0],null)],null)],null)),function(){return function f(e){return new $APP.Ic(null,function(){for(;;){var h=$APP.E(e);if(h){if($APP.kc(h)){var k=$APP.nb(h),l=$APP.I(k),m=new $APP.Kc(Array(l));a:for(var n=0;;)if(n<l){var p=$APP.ac(k,n);p=aj(new $APP.r(null,5,[ni,new $APP.T(null,2,5,$APP.V,[2350,470],null),bj,0,cj,p,dj,0,ej,0],null),vi(new $APP.r(null,4,[wi,"x2",xi,"-30;30",yi,"2s",zi,"indefinite"],null)),vi(new $APP.r(null,4,[wi,"y2",xi,"0;5;0",yi,"2s",zi,"indefinite"],
null)));m.add(p);n+=1}else{k=!0;break a}return k?$APP.Nc(m.O(),f($APP.ob(h))):$APP.Nc(m.O(),null)}m=$APP.F(h);return $APP.R(aj(new $APP.r(null,5,[ni,new $APP.T(null,2,5,$APP.V,[2350,470],null),bj,0,cj,m,dj,0,ej,0],null),vi(new $APP.r(null,4,[wi,"x2",xi,"-30;30",yi,"2s",zi,"indefinite"],null)),vi(new $APP.r(null,4,[wi,"y2",xi,"0;5;0",yi,"2s",zi,"indefinite"],null))),f($APP.Ib(h)))}return null}},null)}(new $APP.T(null,2,5,$APP.V,[-40,40],null))}());return $APP.Y.j(a,fj,new $APP.r(null,3,[$h,c,gj,b,
hj,!1],null))},oj=function(a){return jj(new $APP.r(null,2,[oh,["door-clip-",$APP.y.g(a)].join(""),kj,"userSpaceOnUse"],null),lj(new $APP.r(null,4,[$APP.Hf,a,$APP.Gf,300,mj,30,nj,350],null)))},qj=function(a){return new $APP.r(null,2,[$APP.Gf,150,$h,lj(new $APP.r(null,6,[$APP.Hf,a,$APP.Gf,150,mj,30,nj,150,pj,["url(#door-clip-",$APP.y.g(a),")"].join(""),oi,"rgb(77, 66, 190)"],null))],null)},tj=function(a,b,c){ki.m($h.g($APP.Xb(rj.g(sj.g(a)),b)),$APP.O([$APP.Gf,c]));return Oi(a,new $APP.T(null,4,5,$APP.V,
[sj,rj,b,$APP.Gf],null),c)},uj=function(a){return $APP.tc(function(b,c){ki.m($h.g($APP.Xb(rj.g(sj.g(b)),c)),$APP.O([oi,"rgb(77, 66, 190)"]));return tj(b,c,150)},a,yg())},zj=function(a){if($APP.J.h($APP.Kf.g($APP.Kf.g(a)),vj)){var b=Ji.g(Uh.g(a));return $APP.tc(function(c,d){var e=$APP.Xb(rj.g(sj.g(c)),d),f=$APP.Gf.g(e)+$APP.Xb(wj,d)*xj.g(c);c=tj(c,d,650<f?150:f);$APP.u($APP.hd(Ag(ji,$h.g(e)),b))?(ki.m($h.g(e),$APP.O([oi,"rgb(190, 66, 79)"])),e=ah(c,yj)):e=c;return e},a,yg())}return a},Bj=function(){return gh.h($APP.dg,
function(a){return Z.m(a,uh,Z,Aj,$APP.Y,vh,$APP.O([!0,$APP.Uf,$APP.Uf.g(a)]))})},Hj=function(a){a=Ki($APP.Y.j(a,$APP.Kf,new $APP.r(null,4,[$APP.Kf,vj,$APP.Uf,$APP.Uf.g(a),Cj,new $APP.T(null,3,5,$APP.V,[0,0,0],null),Dj,3],null)));ki.m(Ni.g($APP.Jf.g(a)),$APP.O([oi,"rgb(17, 158, 49)"]));ki.m(Ej.g($APP.Jf.g(a)),$APP.O([oi,"rgb(58, 193, 84)"]));ki.m($h.g($APP.Jf.g(a)),$APP.O([ri,"on"]));a=Z.m(a,$APP.Jf,$APP.Y,Fj,!0,Gj,$APP.O([$APP.Uf.g(a),Pi,!1]));a=Vh(a);ki.m(gj.g(fj.g(a)),$APP.O([oi,"rgb(209, 209, 89)"]));
ki.m($h.g(fj.g(a)),$APP.O([Zi,"yellow"]));a=Z.R(a,fj,$APP.Y,hj,!1);return uj(a)},ek=function(a,b){var c=window.performance.now(),d=Ij.g(a),e=$APP.Uf.g(a);b-=d;d=$APP.Y.j;a=$APP.Y.j(a,xj,b-e);e=vh.g(Jj.g(uh.g(a)));e=$APP.u(e)?$APP.J.h($APP.Uf.g(Jj.g(uh.g(a))),$APP.Uf.g(a)):e;a=$APP.u(e)?Hj(a):a;var f=zj(li(a));if($APP.J.h($APP.Kf.g($APP.Kf.g(f)),vj)){var h=xj.g(f);a=$APP.Uf.g(f);var k=Uh.g(f),l=$APP.Ef.g(uh.g(f)),m=$APP.Lf.g(uh.g(f));e=$APP.Wf.g(uh.g(f));var n=($APP.u(vh.g(l))?-Kj:0)+($APP.u(vh.g(m))?
Kj:0),p=$APP.u(vh.g(e))?.01:0;n=Hi.g(k)+n;n=n<Lj?Lj:n>Mj?Mj:n;h=$APP.Pf.g(k)+h*n;var t=$APP.Hf.g(k),v=$APP.Gf.g(k),A=Qg(Qg(Qg(new $APP.r(null,2,[$APP.Pf,Fi.g(k),$APP.If,Gi.g(k)],null),h,p),Og(t,v,Nj),Oj(Pg(t,v,Nj))),Og(t,v,Pj),Oj(Pg(t,v,Pj)));p=$APP.Pf.g(A);t=$APP.If.g(A);v=$APP.Hf.g(k)+$APP.Nf.g(A);A=$APP.Gf.g(k)+$APP.Mf.g(A);var D=Mi(v,A,h);ki.m($h.g(k),$APP.O([ni,new $APP.T(null,2,5,$APP.V,[v,A],null),qi,h/$APP.eg*180]));ki.m(Qj.g(k),$APP.O([ni,new $APP.T(null,2,5,$APP.V,[v,A],null),qi,p/$APP.eg*
180,ej,-100*t]));ki.m(Ni.g(k),$APP.O([Yi,D]));$APP.gd(Ag(ji,hi.g(ii.g(f))),D)?(f=Z.m(f,Uh,$APP.Y,$APP.Hf,v,$APP.Gf,$APP.O([A,$APP.Pf,h,Fi,p,Gi,t,Hi,n,Ji,D])),l=$APP.J.h($APP.Uf.g(l),a)?Ci(f,$APP.Ef,vh.g(l)):f,m=$APP.J.h($APP.Uf.g(m),a)?Ci(l,$APP.Lf,vh.g(m)):l,a=$APP.J.h($APP.Uf.g(e),a)?Ci(m,$APP.Wf,vh.g(e)):m):a=Ci(Ci(Ci(ah(f,Rj),$APP.Ef,!1),$APP.Lf,!1),$APP.Wf,!1);a=Qi(a)}else a=f;e=Fj.g($APP.Jf.g(a));e=$APP.u(e)?$APP.J.h($APP.Kf.g($APP.Kf.g(a)),vj):e;$APP.u(e)&&(e=$APP.Jf.g(a),m=$APP.ed(e),l=$APP.Q.h(m,
Sj),f=$APP.Q.h(m,Tj),e=$APP.Q.h(m,Ni),m=$APP.Q.h(m,Ej),f=($APP.Uf.g(a)/15%f+f)%f,f=l.getPointAtLength(f),l=f.x,f=f.y,k=5700-$APP.Hf.g(Uh.g(a)),ki.m(e,$APP.O([Xh,l,Yh,f])),ki.m(m,$APP.O([Xh,l,Yh,f])),a=dh(Z.m(a,$APP.Jf,$APP.Y,$APP.Hf,l,$APP.Gf,$APP.O([f])),$APP.Jf,new $APP.r(null,2,[$APP.Vf,Uj(k),$APP.ag,Vj(k)],null)),$APP.u($APP.hd(Ag(ji,Ni.g($APP.Jf.g(a))),Ji.g(Uh.g(a))))&&(ki.m(Ni.g($APP.Jf.g(a)),$APP.O([oi,"rgb(184, 48, 48)"])),ki.m(Ej.g($APP.Jf.g(a)),$APP.O([oi,"rgb(223, 34, 33)"])),a=ah(ch(a,
$APP.Rf),Wj)),a=4900<$APP.Hf.g(Uh.g(a))&&5E3<$APP.Uf.g(a)-Gj.g($APP.Jf.g(a))?Z.R(Vi(a),$APP.Jf,$APP.Y,Gj,$APP.Uf.g(a)):a,$APP.u(Pi.g($APP.Jf.g(a)))&&(ki.m($h.g($APP.Jf.g(a)),$APP.O([ri,"none"])),a=Z.R(ch(fh(a,$APP.Jf,null),$APP.Rf),$APP.Jf,$APP.Y,Fj,!1)));e=a;e=(m=$APP.va(hj.g(fj.g(e))))?$APP.hd(Ag(ji,gj.g(fj.g(e))),Ji.g(Uh.g(e))):m;$APP.u(e)&&(ki.m(gj.g(fj.g(a)),$APP.O([oi,"rgb(90, 90, 38)"])),ki.m($h.g(fj.g(a)),$APP.O([Zi,"rgb(169, 169, 97)"])),a=Z.na(Z.R(a,fj,$APP.Y,hj,!0),$APP.Kf,Z,Dj,Xj,3));
if(e=$APP.J.h($APP.Kf.g($APP.Kf.g(a)),vj))m=Uh.g(a),e=$APP.Hf.g(m),m=$APP.Gf.g(m),e=40>Pg(e,m,Nj)||40>Pg(e,m,Pj);a=e?ah(ch(a,$APP.Rf),Yj):a;e=ki.m;m=Zj.g(ii.g(a));l=$APP.V;f=$APP.Hf.g(Uh.g(a));e.call(ki,m,$APP.O([ni,new $APP.T(null,2,5,l,[500-(5800<f?5800:f),0],null)]));if($APP.J.h($APP.Kf.g($APP.Kf.g(a)),$APP.cg)&&$APP.J.h($APP.Uf.g($APP.Kf.g(a)),$APP.Uf.g(a))){e=ak.g(ii.g(a));b:switch(m=bk instanceof $APP.S?bk.va:null,m){case "crash":m=mi(new $APP.r(null,1,[ni,new $APP.T(null,2,5,$APP.V,[1E3,300],
null)],null),lj(new $APP.r(null,4,[$APP.Hf,-300,$APP.Gf,0,mj,600,nj,400],null)),Sh(new $APP.r(null,3,[$APP.Hf,0,$APP.Gf,50,ck,"middle"],null),$APP.O(["CRASH"])),Sh(new $APP.r(null,3,[$APP.Hf,0,$APP.Gf,150,ck,"middle"],null),$APP.O(["Click this or press \x3cRETURN\x3e"])),Sh(new $APP.r(null,3,[$APP.Hf,0,$APP.Gf,200,ck,"middle"],null),$APP.O(["key to continue"])));break b;default:throw Error(["No matching clause: ",$APP.y.g(m)].join(""));}Zg(m,$APP.Qf,Bj,new $APP.r(null,1,[dk,!0],null));m=$APP.O([mi(new $APP.r(null,
1,[$APP.Sf,"dialog"],null),lj(new $APP.r(null,6,[$APP.Hf,-1E3,$APP.Gf,0,mj,4E3,nj,1E3,Zi,"none",oi,"rgba(0, 0, 0, 0.5)"],null)),m)]);Rh(e,m);a=fh(Di(a),$APP.Jf,null)}if(e=$APP.J.h($APP.Kf.g($APP.Kf.g(a)),$APP.cg))e=vh.g(Aj.g(uh.g(a))),e=$APP.u(e)?$APP.J.h($APP.Uf.g(Aj.g(uh.g(a))),$APP.Uf.g(a)):e;$APP.u(e)&&(Vg(ak.g(ii.g(a)),""),a=Hj(a));c=window.performance.now()-c;l=Cj.g(a);e=$APP.P(l,0,null);m=$APP.P(l,1,null);l=$APP.P(l,2,null);c=$APP.Y.j(a,Cj,new $APP.T(null,3,5,$APP.V,[e>c?e:c,(m*l+c)/(l+1),
l+1],null));return d.call($APP.Y,th(c),$APP.Uf,b)},tk=function(){Gg($APP.O(["init: init game"]));if(0!=window.location.host.lastIndexOf("localhost",0)){var a=navigator.serviceWorker;$APP.u(a)&&(Gg($APP.O(["init: registering worker..."])),a.register("worker.js",{scope:"./"}).then(function(){return Gg($APP.O(["init: worker registered"]))}).catch(function(b){return Gg($APP.O(["init: worker failed",b]))}))}gh.h($APP.dg,function(b){b=$APP.Y.j(Ih(lh($APP.Y.j(b,$APP.Ff,!0))),$APP.Uf,window.performance.now());
var c=Ai(8,-8,90),d=Ai(-8,-8,-90),e=Ai(0,20,0),f=Wi(new $APP.r(null,4,[Zi,"red",Xi,3,oi,"rgb(24, 24, 24)",Yi,Li],null)),h=aj(new $APP.r(null,6,[Zi,"green",Xi,2,bj,0,cj,0,dj,0,ej,0],null)),k=mi(c,d,e);b=$APP.Y.j(b,Uh,new $APP.r(null,7,[Bi,new $APP.r(null,3,[$APP.Ef,c,$APP.Lf,d,$APP.Wf,e],null),Ni,f,Qj,h,$h,k,$APP.Hf,200,$APP.Gf,500,$APP.Pf,$APP.fg],null));c=fk(new $APP.r(null,5,[oh,"ufo-path",Xi,2,Zi,"gray",oi,"none",gk,["M ",$APP.y.g(5700)," ",$APP.y.g(200)," c ",$APP.y.g(300)," 0 ",$APP.y.g(-300),
" ",$APP.y.g(600)," 0 ",$APP.y.g(600)," c ",$APP.y.g(300)," 0 ",$APP.y.g(-300)," ",$APP.y.g(-600)," 0 ",$APP.y.g(-600)].join("")],null));d=si(new $APP.r(null,5,[oi,"rgb(17, 158, 49)",Xh,0,Yh,0,ti,80,ui,15],null));e=si(new $APP.r(null,6,[ni,new $APP.T(null,2,5,$APP.V,[0,-15],null),oi,"rgb(58, 193, 84)",Xh,0,Yh,0,ti,30,ui,10],null));f=mi(d,e);b=$APP.Y.j(b,$APP.Jf,new $APP.r(null,5,[$h,f,Ni,d,Ej,e,Sj,c,Tj,c.getTotalLength()],null));b=ij(b);c=mi(new $APP.r(null,1,[oi,"white"],null));d=mi(new $APP.r(null,
1,[oi,"rgb(0, 255, 49)"],null));b=$APP.Y.j(b,Th,new $APP.r(null,3,[$h,mi(c,d),Uh,c,$APP.Jf,d],null));c=xg(oj);d=xg(qj);b=$APP.Y.j(b,sj,new $APP.r(null,3,[hk,c,rj,d,$h,mi(new $APP.r(null,1,[Zi,"none"],null),$APP.X.h($h,d))],null));b=$APP.Y.j(b,ik,new $APP.r(null,2,[hk,jk(new $APP.r(null,1,[oh,"blackhole-glow"],null),kk(new $APP.r(null,3,[lk,"0%",mk,"rgb(14, 0, 236)",nk,.4],null)),kk(new $APP.r(null,3,[lk,"100%",mk,"rgb(14, 0, 236)",nk,0],null))),$h,mi(pi(Nj),pi(Pj))],null));c=fk(new $APP.r(null,4,
[Zi,"gray",Xi,2,oi,"rgb(24, 24, 24)",gk,"m 2025,850 100,100 h 450 l 300,-300 h 500 l 150,250 h 800 l 150,-250 h 450 l 150,300 H 7125 V 152 l -650,-2 v 550 l 50,50\n   h 350 L 6975,650 V 400 l -50,-50 h -200 l -50,50 v 200 h -50 V 350 l 50,-50 h 300 l 50,50 V 700 L 6925,800 H 6225 L 6075,650\n   V 100 H 5075 L 4925,400 H 4475 L 4335,150 H 3525 L 3375,300 H 2625 V 650 L 2475,800 H 2175 V 600 h 300 V 350 H 2175 L 2025,450\n   V 700 H 1325 L 775,500 1325,300 h 700 V 150 H 775 L 275,350 h -500 v 300 h 500 l 500,200 Z"],
null));d=ok(new $APP.r(null,6,[oh,"soil-pattern",$APP.Hf,0,$APP.Gf,0,mj,100,nj,100,pk,"userSpaceOnUse"],null),fk(new $APP.r(null,2,[oi,"rgb(73, 73, 73)",gk,"M11,18 C14.8659932,18 18,14.8659932 18,11 C18,7.13400675 14.8659932,4 11,4 C7.13400675,4 4,7.13400675 4,11\n   C4,14.8659932 7.13400675,18 11,18 Z M59,43 C62.8659932,43 66,39.8659932 66,36 C66,32.1340068 62.8659932,29 59,29\n   C55.1340068,29 52,32.1340068 52,36 C52,39.8659932 55.1340068,43 59,43 Z M16,36 C17.6568542,36 19,34.6568542 19,33\n   C19,31.3431458 17.6568542,30 16,30 C14.3431458,30 13,31.3431458 13,33 C13,34.6568542 14.3431458,36 16,36 Z M79,67\n   C80.6568542,67 82,65.6568542 82,64 C82,62.3431458 80.6568542,61 79,61 C77.3431458,61 76,62.3431458 76,64\n   C76,65.6568542 77.3431458,67 79,67 Z M34,90 C35.6568542,90 37,88.6568542 37,87 C37,85.3431458 35.6568542,84 34,84\n   C32.3431458,84 31,85.3431458 31,87 C31,88.6568542 32.3431458,90 34,90 Z M90,14 C91.6568542,14 93,12.6568542 93,11\n   C93,9.34314575 91.6568542,8 90,8 C88.3431458,8 87,9.34314575 87,11 C87,12.6568542 88.3431458,14 90,14 Z M12,86\n   C14.209139,86 16,84.209139 16,82 C16,79.790861 14.209139,78 12,78 C9.790861,78 8,79.790861 8,82 C8,84.209139 9.790861,86 12,86 Z\n   M40,21 C42.209139,21 44,19.209139 44,17 C44,14.790861 42.209139,13 40,13 C37.790861,13 36,14.790861 36,17\n   C36,19.209139 37.790861,21 40,21 Z M63,10 C65.7614237,10 68,7.76142375 68,5 C68,2.23857625 65.7614237,0 63,0\n   C60.2385763,0 58,2.23857625 58,5 C58,7.76142375 60.2385763,10 63,10 Z M57,70 C59.209139,70 61,68.209139 61,66\n   C61,63.790861 59.209139,62 57,62 C54.790861,62 53,63.790861 53,66 C53,68.209139 54.790861,70 57,70 Z M86,92\n   C88.7614237,92 91,89.7614237 91,87 C91,84.2385763 88.7614237,82 86,82 C83.2385763,82 81,84.2385763 81,87\n   C81,89.7614237 83.2385763,92 86,92 Z M32,63 C34.7614237,63 37,60.7614237 37,58 C37,55.2385763 34.7614237,53 32,53\n   C29.2385763,53 27,55.2385763 27,58 C27,60.7614237 29.2385763,63 32,63 Z M89,50 C91.7614237,50 94,47.7614237 94,45\n   C94,42.2385763 91.7614237,40 89,40 C86.2385763,40 84,42.2385763 84,45 C84,47.7614237 86.2385763,50 89,50 Z M80,29\n   C81.1045695,29 82,28.1045695 82,27 C82,25.8954305 81.1045695,25 80,25 C78.8954305,25 78,25.8954305 78,27\n   C78,28.1045695 78.8954305,29 80,29 Z M60,91 C61.1045695,91 62,90.1045695 62,89 C62,87.8954305 61.1045695,87 60,87\n   C58.8954305,87 58,87.8954305 58,89 C58,90.1045695 58.8954305,91 60,91 Z M35,41 C36.1045695,41 37,40.1045695 37,39\n   C37,37.8954305 36.1045695,37 35,37 C33.8954305,37 33,37.8954305 33,39 C33,40.1045695 33.8954305,41 35,41 Z\n   M12,60 C13.1045695,60 14,59.1045695 14,58 C14,56.8954305 13.1045695,56 12,56 C10.8954305,56 10,56.8954305 10,58\n   C10,59.1045695 10.8954305,60 12,60 Z"],
null)));f=mi(lj(new $APP.r(null,5,[$APP.Hf,-1E3,$APP.Gf,-1E3,mj,1E4,nj,3E3,oi,"url(#soil-pattern)"],null)));e=mi(new $APP.r(null,3,[Zi,"red",Xi,4,oi,"rgb(24, 24, 24)"],null));f=mi(f,c,$h.g(sj.g(b)),$h.g(fj.g(b)),$h.g(ik.g(b)),$h.g(Th.g(b)),Ni.g(Uh.g(b)),$h.g(Uh.g(b)),Qj.g(Uh.g(b)),$h.g($APP.Jf.g(b)));h=mi(new $APP.r(null,1,[oh,"scene"],null),f,e);Wg(Vg("game",""),new $APP.T(null,2,5,$APP.V,[qk(d,hk.g(sj.g(b)),hk.g(ik.g(b))),h],null));b=$APP.Y.j(b,ii,new $APP.r(null,4,[ii,h,Zj,f,hi,c,ak,e],null));
b=Hj(b);$g(window,rk,Ti);setTimeout(Ti,0);b=$APP.Y.j(b,rh,!1);window.requestAnimationFrame(sk);return b});return Gg($APP.O(["init: done"]))},uk=function uk(a,b,c){var e=a.l-2>>>b&31;if(5<b){b-=5;var f=c.i[e];a=uk.j?uk.j(a,b,f):uk.call(null,a,b,f);if(null==a&&0===e)return null;c=$APP.nd(c);c.i[e]=a;return c}if(0===e)return null;c=$APP.nd(c);c.i[e]=null;return c};
$APP.de.prototype.Fa=ng(15,function(a,b,c){var d=1<<(b>>>a&31);if(0===(this.M&d))return this;var e=$APP.Cc(this.M&d-1),f=this.i[2*e],h=this.i[2*e+1];return null==f?(a=h.Fa(a+5,b,c),a===h?this:null!=a?new $APP.de(null,this.M,$APP.$d(this.i,2*e+1,a)):this.M===d?null:new $APP.de(null,this.M^d,og(this.i,e))):$APP.Sd(c,f)?this.M===d?null:new $APP.de(null,this.M^d,og(this.i,e)):this});
$APP.fe.prototype.Fa=ng(14,function(a,b,c){var d=b>>>a&31,e=this.i[d];if(null!=e){a=e.Fa(a+5,b,c);if(a===e)d=this;else if(null==a)if(8>=this.l)a:{e=this.i;a=e.length;b=Array(2*(this.l-1));c=0;for(var f=1,h=0;;)if(c<a)c!==d&&null!=e[c]?(b[f]=e[c],f+=2,h|=1<<c,c+=1):c+=1;else{d=new $APP.de(null,h,b);break a}}else d=new $APP.fe(null,this.l-1,$APP.$d(this.i,d,a));else d=new $APP.fe(null,this.l,$APP.$d(this.i,d,a));return d}return this});
$APP.he.prototype.Fa=ng(13,function(a,b,c){a=$APP.ge(this.i,this.l,c);return-1===a?this:1===this.l?null:new $APP.he(null,this.za,this.l-1,og(this.i,$APP.Bc(a)))});$APP.r.prototype.jb=ng(12,function(a,b){if(0<=$APP.Od(this.i,b)){a=this.i.length;var c=a-2;if(0===c)return this.Z(null);c=Array(c);for(var d=0,e=0;;){if(d>=a)return new $APP.r(this.u,this.l-1,c,null);$APP.J.h(b,this.i[d])?d+=2:(c[e]=this.i[d],c[e+1]=this.i[d+1],e+=2,d+=2)}}else return this});
$APP.ve.prototype.jb=ng(11,function(a,b){if(null==b)return this.ha?new $APP.ve(this.u,this.l-1,this.root,!1,null,null):this;if(null==this.root)return this;a=this.root.Fa(0,$APP.Cb(b),b);return a===this.root?this:new $APP.ve(this.u,this.l-1,a,this.ha,this.ia,null)});$APP.Ec.prototype.ya=ng(10,function(){return this.fa(null)});$APP.Fc.prototype.ya=ng(9,function(){throw Error("Can't pop empty list");});
$APP.T.prototype.ya=ng(8,function(){if(0===this.l)throw Error("Can't pop empty vector");if(1===this.l)return $APP.Va($APP.yd,this.u);if(1<this.l-$APP.od(this))return new $APP.T(this.u,this.l-1,this.shift,this.root,this.ja.slice(0,-1),null);var a=$APP.qd(this,this.l-2),b=uk(this,this.shift,this.root);b=null==b?$APP.V:b;var c=this.l-1;return 5<this.shift&&null==b.i[1]?new $APP.T(this.u,c,this.shift-5,b.i[0],a,null):new $APP.T(this.u,c,this.shift,b,a,null)});
$APP.Pd.prototype.ya=ng(7,function(){return new $APP.T(null,1,5,$APP.V,[this.key],null)});$APP.Ec.prototype.xa=ng(6,function(){return this.first});$APP.Fc.prototype.xa=ng(5,function(){return null});$APP.T.prototype.xa=ng(4,function(){return 0<this.l?this.J(null,this.l-1):null});$APP.Pd.prototype.xa=ng(3,function(){return this.V});$APP.C.prototype.Wa=ng(2,function(){var a=this.P(null);return 0<a?new $APP.$b(this,a-1,null):null});
$APP.T.prototype.Wa=ng(1,function(){return 0<this.l?new $APP.$b(this,this.l-1,null):null});$APP.Pd.prototype.Wa=ng(0,function(){return new $APP.C([this.V,this.key],0,null)});var Xj=function Xj(a){switch(arguments.length){case 0:return Xj.C();case 1:return Xj.g(arguments[0]);case 2:return Xj.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Xj.m(arguments[0],arguments[1],new $APP.C(c.slice(2),0,null))}};Xj.C=function(){return 0};
Xj.g=function(a){return a};Xj.h=function(a,b){return a+b};Xj.m=function(a,b,c){return $APP.tc(Xj,a+b,c)};Xj.F=function(a){var b=$APP.F(a),c=$APP.H(a);a=$APP.F(c);c=$APP.H(c);return this.m(b,a,c)};Xj.H=2;var eh=function eh(a){switch(arguments.length){case 1:return eh.g(arguments[0]);case 2:return eh.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return eh.m(arguments[0],arguments[1],new $APP.C(c.slice(2),0,null))}};eh.g=function(a){return a};
eh.h=function(a,b){return null==a?null:qg(a,b)};eh.m=function(a,b,c){for(;;){if(null==a)return null;a=eh.h(a,b);if($APP.u(c))b=$APP.F(c),c=$APP.H(c);else return a}};eh.F=function(a){var b=$APP.F(a),c=$APP.H(a);a=$APP.F(c);c=$APP.H(c);return this.m(b,a,c)};eh.H=2;
var Oi=function Oi(a,b,c){var e=$APP.E(b);b=$APP.F(e);var f=$APP.H(e);if(f){e=$APP.Y.j;var h=$APP.Q.h(a,b);c=Oi.j?Oi.j(h,f,c):Oi.call(null,h,f,c);a=e.call($APP.Y,a,b,c)}else a=$APP.Y.j(a,b,c);return a},Z=function Z(a){switch(arguments.length){case 3:return Z.j(arguments[0],arguments[1],arguments[2]);case 4:return Z.B(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return Z.R(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);case 6:return Z.na(arguments[0],arguments[1],
arguments[2],arguments[3],arguments[4],arguments[5]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Z.m(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],new $APP.C(c.slice(6),0,null))}};Z.j=function(a,b,c){var d=$APP.Y.j,e=$APP.Q.h(a,b);c=c.g?c.g(e):c.call(null,e);return d.call($APP.Y,a,b,c)};Z.B=function(a,b,c,d){var e=$APP.Y.j,f=$APP.Q.h(a,b);c=c.h?c.h(f,d):c.call(null,f,d);return e.call($APP.Y,a,b,c)};
Z.R=function(a,b,c,d,e){var f=$APP.Y.j,h=$APP.Q.h(a,b);c=c.j?c.j(h,d,e):c.call(null,h,d,e);return f.call($APP.Y,a,b,c)};Z.na=function(a,b,c,d,e,f){var h=$APP.Y.j,k=$APP.Q.h(a,b);c=c.B?c.B(k,d,e,f):c.call(null,k,d,e,f);return h.call($APP.Y,a,b,c)};Z.m=function(a,b,c,d,e,f,h){return $APP.Y.j(a,b,$APP.$c(c,$APP.Q.h(a,b),d,e,f,$APP.O([h])))};
Z.F=function(a){var b=$APP.F(a),c=$APP.H(a);a=$APP.F(c);var d=$APP.H(c);c=$APP.F(d);var e=$APP.H(d);d=$APP.F(e);var f=$APP.H(e);e=$APP.F(f);var h=$APP.H(f);f=$APP.F(h);h=$APP.H(h);return this.m(b,a,c,d,e,f,h)};Z.H=6;
var ei=function ei(a){switch(arguments.length){case 3:return ei.j(arguments[0],arguments[1],arguments[2]);case 4:return ei.B(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return ei.R(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);case 6:return ei.na(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return ei.m(arguments[0],arguments[1],arguments[2],
arguments[3],arguments[4],arguments[5],new $APP.C(c.slice(6),0,null))}};ei.j=function(a,b,c){var d=$APP.E(b);b=$APP.F(d);if(d=$APP.H(d))a=$APP.Y.j(a,b,ei.j($APP.Q.h(a,b),d,c));else{d=$APP.Y.j;var e=$APP.Q.h(a,b);c=c.g?c.g(e):c.call(null,e);a=d.call($APP.Y,a,b,c)}return a};ei.B=function(a,b,c,d){var e=$APP.E(b);b=$APP.F(e);if(e=$APP.H(e))a=$APP.Y.j(a,b,ei.B($APP.Q.h(a,b),e,c,d));else{e=$APP.Y.j;var f=$APP.Q.h(a,b);c=c.h?c.h(f,d):c.call(null,f,d);a=e.call($APP.Y,a,b,c)}return a};
ei.R=function(a,b,c,d,e){var f=$APP.E(b);b=$APP.F(f);if(f=$APP.H(f))a=$APP.Y.j(a,b,ei.R($APP.Q.h(a,b),f,c,d,e));else{f=$APP.Y.j;var h=$APP.Q.h(a,b);c=c.j?c.j(h,d,e):c.call(null,h,d,e);a=f.call($APP.Y,a,b,c)}return a};ei.na=function(a,b,c,d,e,f){var h=$APP.E(b);b=$APP.F(h);if(h=$APP.H(h))a=$APP.Y.j(a,b,ei.na($APP.Q.h(a,b),h,c,d,e,f));else{h=$APP.Y.j;var k=$APP.Q.h(a,b);c=c.B?c.B(k,d,e,f):c.call(null,k,d,e,f);a=h.call($APP.Y,a,b,c)}return a};
ei.m=function(a,b,c,d,e,f,h){var k=$APP.E(b);b=$APP.F(k);return(k=$APP.H(k))?$APP.Y.j(a,b,$APP.$c(ei,$APP.Q.h(a,b),k,c,d,$APP.O([e,f,h]))):$APP.Y.j(a,b,$APP.$c(c,$APP.Q.h(a,b),d,e,f,$APP.O([h])))};ei.F=function(a){var b=$APP.F(a),c=$APP.H(a);a=$APP.F(c);var d=$APP.H(c);c=$APP.F(d);var e=$APP.H(d);d=$APP.F(e);var f=$APP.H(e);e=$APP.F(f);var h=$APP.H(f);f=$APP.F(h);h=$APP.H(h);return this.m(b,a,c,d,e,f,h)};ei.H=6;
var Bg=function Bg(a,b){var d=a.exec(b);if(null==d)return null;var e=d[0],f=1===d.length?e:$APP.zd(d);return $APP.R(f,new $APP.Ic(null,function(){var h=e.length;h=d.index+(1>h?1:h);return h<=b.length?(h=b.substring(h),Bg.h?Bg.h(a,h):Bg.call(null,a,h)):null},null))},vk=function vk(a){switch(arguments.length){case 0:return vk.C();case 1:return vk.g(arguments[0]);case 2:return vk.h(arguments[0],arguments[1]);case 3:return vk.j(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,
e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return vk.m(arguments[0],arguments[1],arguments[2],new $APP.C(c.slice(3),0,null))}};vk.C=function(){return $APP.Ac};vk.g=function(a){return a};
vk.h=function(a,b){return function(){function c(l,m,n){l=b.j?b.j(l,m,n):b.call(null,l,m,n);return a.g?a.g(l):a.call(null,l)}function d(l,m){l=b.h?b.h(l,m):b.call(null,l,m);return a.g?a.g(l):a.call(null,l)}function e(l){l=b.g?b.g(l):b.call(null,l);return a.g?a.g(l):a.call(null,l)}function f(){var l=b.C?b.C():b.call(null);return a.g?a.g(l):a.call(null,l)}var h=null,k=function(){function l(n,p,t,v){var A=null;if(3<arguments.length){A=0;for(var D=Array(arguments.length-3);A<D.length;)D[A]=arguments[A+
3],++A;A=new $APP.C(D,0,null)}return m.call(this,n,p,t,A)}function m(n,p,t,v){n=$APP.Zc(b,n,p,t,v);return a.g?a.g(n):a.call(null,n)}l.H=3;l.F=function(n){var p=$APP.F(n);n=$APP.H(n);var t=$APP.F(n);n=$APP.H(n);var v=$APP.F(n);n=$APP.Ib(n);return m(p,t,v,n)};l.m=m;return l}();h=function(l,m,n,p){switch(arguments.length){case 0:return f.call(this);case 1:return e.call(this,l);case 2:return d.call(this,l,m);case 3:return c.call(this,l,m,n);default:var t=null;if(3<arguments.length){t=0;for(var v=Array(arguments.length-
3);t<v.length;)v[t]=arguments[t+3],++t;t=new $APP.C(v,0,null)}return k.m(l,m,n,t)}throw Error("Invalid arity: "+arguments.length);};h.H=3;h.F=k.F;h.C=f;h.g=e;h.h=d;h.j=c;h.m=k.m;return h}()};
vk.j=function(a,b,c){return function(){function d(m,n,p){m=c.j?c.j(m,n,p):c.call(null,m,n,p);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}function e(m,n){m=c.h?c.h(m,n):c.call(null,m,n);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}function f(m){m=c.g?c.g(m):c.call(null,m);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}function h(){var m=c.C?c.C():c.call(null);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}var k=null,l=function(){function m(p,
t,v,A){var D=null;if(3<arguments.length){D=0;for(var M=Array(arguments.length-3);D<M.length;)M[D]=arguments[D+3],++D;D=new $APP.C(M,0,null)}return n.call(this,p,t,v,D)}function n(p,t,v,A){p=$APP.Zc(c,p,t,v,A);p=b.g?b.g(p):b.call(null,p);return a.g?a.g(p):a.call(null,p)}m.H=3;m.F=function(p){var t=$APP.F(p);p=$APP.H(p);var v=$APP.F(p);p=$APP.H(p);var A=$APP.F(p);p=$APP.Ib(p);return n(t,v,A,p)};m.m=n;return m}();k=function(m,n,p,t){switch(arguments.length){case 0:return h.call(this);case 1:return f.call(this,
m);case 2:return e.call(this,m,n);case 3:return d.call(this,m,n,p);default:var v=null;if(3<arguments.length){v=0;for(var A=Array(arguments.length-3);v<A.length;)A[v]=arguments[v+3],++v;v=new $APP.C(A,0,null)}return l.m(m,n,p,v)}throw Error("Invalid arity: "+arguments.length);};k.H=3;k.F=l.F;k.C=h;k.g=f;k.h=e;k.j=d;k.m=l.m;return k}()};
vk.m=function(a,b,c,d){var e=Fg($APP.R(a,$APP.R(b,$APP.R(c,d))));return function(){function f(k){var l=null;if(0<arguments.length){l=0;for(var m=Array(arguments.length-0);l<m.length;)m[l]=arguments[l+0],++l;l=new $APP.C(m,0,null)}return h.call(this,l)}function h(k){k=$APP.Wc($APP.F(e),k);for(var l=$APP.H(e);;)if(l){var m=$APP.F(l);k=m.g?m.g(k):m.call(null,k);l=$APP.H(l)}else return k}f.H=0;f.F=function(k){k=$APP.E(k);return h(k)};f.m=h;return f}()};
vk.F=function(a){var b=$APP.F(a),c=$APP.H(a);a=$APP.F(c);var d=$APP.H(c);c=$APP.F(d);d=$APP.H(d);return this.m(b,a,c,d)};vk.H=3;
var gh=function gh(a){switch(arguments.length){case 2:return gh.h(arguments[0],arguments[1]);case 3:return gh.j(arguments[0],arguments[1],arguments[2]);case 4:return gh.B(arguments[0],arguments[1],arguments[2],arguments[3]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return gh.m(arguments[0],arguments[1],arguments[2],arguments[3],new $APP.C(c.slice(4),0,null))}};
gh.h=function(a,b){if(a instanceof $APP.id){var c=a.state;b=b.g?b.g(c):b.call(null,c);a=Hg(a,b)}else a=$APP.rf(a,b);return a};gh.j=function(a,b,c){if(a instanceof $APP.id){var d=a.state;b=b.h?b.h(d,c):b.call(null,d,c);a=Hg(a,b)}else a=$APP.rf(a,b,c);return a};gh.B=function(a,b,c,d){if(a instanceof $APP.id){var e=a.state;b=b.j?b.j(e,c,d):b.call(null,e,c,d);a=Hg(a,b)}else a=$APP.rf(a,b,c,d);return a};
gh.m=function(a,b,c,d,e){return a instanceof $APP.id?Hg(a,$APP.Zc(b,a.state,c,d,e)):$APP.rf(a,b,c,d,e)};gh.F=function(a){var b=$APP.F(a),c=$APP.H(a);a=$APP.F(c);var d=$APP.H(c);c=$APP.F(d);var e=$APP.H(d);d=$APP.F(e);e=$APP.H(e);return this.m(b,a,c,d,e)};gh.H=4;Ig.prototype.vb=function(){$APP.u(this.f)&&(this.value=this.f.C?this.f.C():this.f.call(null),this.f=null);return this.value};
Ig.prototype.S=function(a,b,c){$APP.fb(b,"#object[cljs.core.Delay ");$APP.Ue(new $APP.r(null,2,[$APP.Kf,null==this.f?$APP.bg:$APP.Tf,$APP.Bf,this.value],null),b,c);return $APP.fb(b,"]")};
var ej=new $APP.S(null,"y2","y2",-718691301),cj=new $APP.S(null,"y1","y1",589123466),ni=new $APP.S(null,"translate","translate",1336199447),Gj=new $APP.S(null,"shoot-ts","shoot-ts",800795585),di=new $APP.S(null,"action","action",-811238024),Nh=new $APP.S(null,"transform","transform",1381301764),Zh=new $APP.S(null,"r","r",-471384190),yi=new $APP.S(null,"dur","dur",1464522452),pj=new $APP.S(null,"clip-path","clip-path",-439959120),Tg=new $APP.S(null,"style","style",-496642736),Hh=new $APP.S(null,"keyup",
"keyup",-794526927),wi=new $APP.S(null,"attributeName","attributeName",-400177890),zi=new $APP.S(null,"repeatCount","repeatCount",1447663848),$h=new $APP.S(null,"g","g",1738089905),gk=new $APP.S(null,"d","d",1972142424),bj=new $APP.S(null,"x1","x1",-1863922247),Fi=new $APP.S(null,"vh","vh",79552846),gj=new $APP.S(null,"body","body",-2049205669),sj=new $APP.S(null,"door","door",-956406127),mj=new $APP.S(null,"width","width",-384071477),fj=new $APP.S(null,"diamond","diamond",2136949587),dj=new $APP.S(null,
"x2","x2",-1362513475),Gi=new $APP.S(null,"vs","vs",-2022097090),pk=new $APP.S(null,"patternUnits","patternUnits",-1458803100),uh=new $APP.S(null,"control","control",1892578036),Zj=new $APP.S(null,"board","board",-1907017633),Dj=new $APP.S(null,"lives","lives",845902073),mk=new $APP.S(null,"stop-color","stop-color",316173955),hj=new $APP.S(null,"captured?","captured?",-327560235),dk=new $APP.S(null,"once","once",-262568523),qi=new $APP.S(null,"rotate","rotate",152705015),Yh=new $APP.S(null,"cy","cy",
755331060),Xh=new $APP.S(null,"cx","cx",1272694324),Qj=new $APP.S(null,"speed","speed",1257663751),bk=new $APP.S(null,"crash","crash",-1024911330),Yi=new $APP.S(null,"points","points",-1486596883),Dh=new $APP.S(null,"touchend","touchend",-1574059019),Fj=new $APP.S(null,"active?","active?",459499776),Rj=new $APP.S(null,"cave-collision","cave-collision",1745878817),ak=new $APP.S(null,"dialogs","dialogs",-2046256986),Hi=new $APP.S(null,"dh","dh",528137731),ck=new $APP.S(null,"text-anchor","text-anchor",
585613696),xj=new $APP.S(null,"dt","dt",-368444759),Cj=new $APP.S(null,"timing","timing",-1849225195),Ah=new $APP.S(null,"mousedown","mousedown",1391242074),lk=new $APP.S(null,"offset","offset",296498311),Ui=new $APP.S(null,"ufo-bullet","ufo-bullet",1862433478),Uh=new $APP.S(null,"ship","ship",197863473),yj=new $APP.S(null,"door-collision","door-collision",-2141343471),ri=new $APP.S(null,"display","display",242065432),xi=new $APP.S(null,"values","values",372645556),ii=new $APP.S(null,"scene","scene",
1523800415),Sj=new $APP.S(null,"path","path",-188191168),ui=new $APP.S(null,"ry","ry",-334598563),ti=new $APP.S(null,"rx","rx",1627208482),Wj=new $APP.S(null,"ufo-collision","ufo-collision",1365566601),wk=new $APP.S(null,"skew","skew",-595121815),vh=new $APP.S(null,"on","on",173873944),hk=new $APP.S(null,"defs","defs",1398449717),kj=new $APP.S(null,"clipPathUnits","clipPathUnits",-1747479222),Ri=new $APP.S(null,"viewBox","viewBox",-469489477),Th=new $APP.S(null,"bullets","bullets",1734809024),rh=
new $APP.S(null,"debug-on?","debug-on?",655904671),Ch=new $APP.S(null,"touchstart","touchstart",369858804),Aj=new $APP.S(null,"continue","continue",-207346553),ai=new $APP.S(null,"pt","pt",556460867),Gh=new $APP.S(null,"keydown","keydown",-629268186),Ii=new $APP.S(null,"fire-ts","fire-ts",450810921),nj=new $APP.S(null,"height","height",1025178622),Xi=new $APP.S(null,"stroke-width","stroke-width",716836435),jh=new $APP.S(null,"is-fullscreen?","is-fullscreen?",972486782),Bh=new $APP.S(null,"mouseup",
"mouseup",350619456),Tj=new $APP.S(null,"path-len","path-len",-1558209254),oi=new $APP.S(null,"fill","fill",883462889),Jj=new $APP.S(null,"reset","reset",-800929946),hi=new $APP.S(null,"cave","cave",-587603287),Si=new $APP.S(null,"scale","scale",-230427353),Ej=new $APP.S(null,"cockpit","cockpit",1450878936),nk=new $APP.S(null,"stop-opacity","stop-opacity",-2018003729),kh=new $APP.S(null,"can-fullscreen?","can-fullscreen?",-1592427507),Ij=new $APP.S(null,"start-time","start-time",814801386),rj=new $APP.S(null,
"doors","doors",-381344314),vj=new $APP.S(null,"run","run",-1821166653),Yj=new $APP.S(null,"blackhole-collision","blackhole-collision",629928693),Ni=new $APP.S(null,"hull","hull",-957096876),ik=new $APP.S(null,"blackhole","blackhole",2025585951),Zi=new $APP.S(null,"stroke","stroke",1741823555),Eh=new $APP.S(null,"touchcancel","touchcancel",-669291029),oh=new $APP.S(null,"id","id",-1388402092),Ji=new $APP.S(null,"hull-points","hull-points",263796144),Bi=new $APP.S(null,"thruster","thruster",-2030069641),
ci=new $APP.S(null,"target","target",253001721),Pi=new $APP.S(null,"killed","killed",702860541),rk=new $APP.S(null,"resize","resize",297367086);var ph=new $APP.T(null,15,5,$APP.V,[new $APP.T(null,2,5,$APP.V,["status",new $APP.T(null,2,5,$APP.V,[$APP.Kf,function(a){var b=$APP.ed(a);a=$APP.Q.h(b,$APP.Kf);b=$APP.Q.h(b,$APP.Yf);return[$APP.He(a),$APP.u(b)?[" (",$APP.He(b),")"].join(""):null].join("")}],null)],null),new $APP.T(null,2,5,$APP.V,["timing",new $APP.T(null,2,5,$APP.V,[Cj,function(a){var b=$APP.P(a,0,null);a=$APP.P(a,1,null);return["max: ",$APP.y.g(b.toFixed(1))," avg: ",$APP.y.g(a.toFixed(1))].join("")}],null)],null),new $APP.T(null,
2,5,$APP.V,["dt",new $APP.T(null,2,5,$APP.V,[xj,mh],null)],null),new $APP.T(null,2,5,$APP.V,["x",new $APP.T(null,3,5,$APP.V,[Uh,$APP.Hf,mh],null)],null),new $APP.T(null,2,5,$APP.V,["y",new $APP.T(null,3,5,$APP.V,[Uh,$APP.Gf,mh],null)],null),new $APP.T(null,2,5,$APP.V,["vh",new $APP.T(null,3,5,$APP.V,[Uh,Fi,mh],null)],null),new $APP.T(null,2,5,$APP.V,["vs",new $APP.T(null,3,5,$APP.V,[Uh,Gi,mh],null)],null),new $APP.T(null,2,5,$APP.V,["h",new $APP.T(null,3,5,$APP.V,[Uh,$APP.Pf,mh],null)],null),new $APP.T(null,
2,5,$APP.V,["dh",new $APP.T(null,3,5,$APP.V,[Uh,Hi,mh],null)],null),new $APP.T(null,2,5,$APP.V,["left",new $APP.T(null,4,5,$APP.V,[uh,$APP.Ef,vh,nh],null)],null),new $APP.T(null,2,5,$APP.V,["right",new $APP.T(null,4,5,$APP.V,[uh,$APP.Lf,vh,nh],null)],null),new $APP.T(null,2,5,$APP.V,["forward",new $APP.T(null,4,5,$APP.V,[uh,$APP.Wf,vh,nh],null)],null),new $APP.T(null,2,5,$APP.V,["cannon",new $APP.T(null,4,5,$APP.V,[uh,$APP.$f,vh,nh],null)],null),new $APP.T(null,2,5,$APP.V,["ufo active",new $APP.T(null,
3,5,$APP.V,[$APP.Jf,Fj,nh],null)],null),new $APP.T(null,2,5,$APP.V,["lives",new $APP.T(null,2,5,$APP.V,[$APP.Kf,Dj],null)],null)],null);var xh=function(){var a=new $APP.r(null,6,["ArrowUp",wh($APP.Wf),"ArrowLeft",wh($APP.Ef),"ArrowRight",wh($APP.Lf),"Space",wh($APP.$f),"Enter",wh(Aj),"KeyS",function(b){return $APP.u(b)?hh():null}],null);return 0==window.location.host.lastIndexOf("localhost",0)?$APP.Y.m(a,"KeyD",function(b){return $APP.u(b)?sh():null},$APP.O(["KeyR",wh(Jj)])):a}();var Kh=new $APP.T(null,4,5,$APP.V,[ni,qi,Si,wk],null),Ph=$APP.Ge(Kh),xk=$APP.jd.h(Ph,Nh),ki=function ki(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return ki.m(arguments[0],1<c.length?new $APP.C(c.slice(1),0,null):null)};
ki.m=function(a,b){var c=Rg(a);$APP.E(b)&&(a=function(){for(var d=$APP.E(b),e=$APP.F(d),f=$APP.H(d),h=$APP.F(f),k=$APP.H(f),l=$APP.yd,m=b;;){var n=l,p=m,t=$APP.E(p),v=$APP.F(t),A=$APP.H(t),D=v,M=$APP.F(A),U=$APP.H(A),W=M,ea=U;if($APP.va(D))return n;var sa=xk.g?xk.g(D):xk.call(null,D);$APP.u(sa)||($APP.J.h(D,Yi)&&$APP.gc(W)?c.setAttribute("points",$APP.tc($APP.gc($APP.F(W))?function(){return function(Ja,zb){var Dk=$APP.P(zb,0,null);zb=$APP.P(zb,1,null);return[$APP.y.g(Ja),$APP.y.g(Dk),",",$APP.y.g(zb),
" "].join("")}}(l,m,sa,n,p,t,v,A,D,M,U,W,ea,$APP.yd,b,b,d,e,f,e,h,k,h,k,c):function(){return function(Ja,zb){return[$APP.y.g(Ja),$APP.y.g(zb.x),",",$APP.y.g(zb.y)," "].join("")}}(l,m,sa,n,p,t,v,A,D,M,U,W,ea,$APP.yd,b,b,d,e,f,e,h,k,h,k,c),"",W)):c.setAttribute($APP.He(D),$APP.y.g(W)));l=$APP.u(sa)?$APP.jd.h(n,new $APP.T(null,2,5,$APP.V,[D,W],null)):n;m=ea}}(),$APP.E(a)&&Qh(c,a));return c};ki.H=1;ki.F=function(a){var b=$APP.F(a);a=$APP.H(a);return this.m(b,a)};
var yk=function yk(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return yk.m(arguments[0],1<c.length?new $APP.C(c.slice(1),0,null):null)};
yk.m=function(a,b){a=document.createElementNS("http://www.w3.org/2000/svg",a);var c=$APP.hc($APP.F(b))?new $APP.T(null,2,5,$APP.V,[$APP.F(b),$APP.Ib(b)],null):new $APP.T(null,2,5,$APP.V,[null,b],null);b=$APP.P(c,0,null);c=$APP.P(c,1,null);a.translate=new $APP.T(null,2,5,$APP.V,[0,0],null);a.rotate=0;a.scale=1;b=$APP.Wc($APP.vf,$APP.Xc($APP.X,$APP.Ac,$APP.O([b])));$APP.Xc(ki,a,b);b=$APP.E(c);c=null;for(var d=0,e=0;;)if(e<d){var f=c.J(null,e);$APP.gc(f)?Rh(a,f):Rh(a,$APP.O([f]));e+=1}else if(b=$APP.E(b))c=
b,$APP.kc(c)?(b=$APP.nb(c),e=$APP.ob(c),c=b,d=$APP.I(b),b=e):(b=$APP.F(c),$APP.gc(b)?Rh(a,b):Rh(a,$APP.O([b])),b=$APP.H(c),c=null,d=0),e=0;else break;return a};yk.H=1;yk.F=function(a){var b=$APP.F(a);a=$APP.H(a);return this.m(b,a)};
var mi=Ag(yk,"g"),Wh=Ag(yk,"circle"),si=Ag(yk,"ellipse"),lj=Ag(yk,"rect"),fk=Ag(yk,"path"),aj=Ag(yk,"line"),$i=Ag(yk,"polyline"),Wi=Ag(yk,"polygon"),qk=Ag(yk,"defs"),jj=Ag(yk,"clipPath"),ok=Ag(yk,"pattern"),jk=Ag(yk,"radialGradient"),kk=Ag(yk,"stop"),vi=Ag(yk,"animate"),bi=function(){try{return Wh($APP.dd).isPointInFill(DOMPoint(0,0)),function(){function b(e,f){return new DOMPoint(e,f)}function c(){return new DOMPoint}var d=null;d=function(e,f){switch(arguments.length){case 0:return c.call(this);
case 2:return b.call(this,e,f)}throw Error("Invalid arity: "+arguments.length);};d.C=c;d.h=b;return d}()}catch(b){var a=new Ig(function(){return yk("svg")});return function(){function c(f,h){var k=$APP.Sa(a).createSVGPoint();k.x=f;k.y=h;return k}function d(){return $APP.Sa(a).createSVGPoint()}var e=null;e=function(f,h){switch(arguments.length){case 0:return d.call(this);case 2:return c.call(this,f,h)}throw Error("Invalid arity: "+arguments.length);};e.C=d;e.h=c;return e}()}}(),ji=function ji(a){switch(arguments.length){case 2:return ji.h(arguments[0],
arguments[1]);case 3:return ji.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.y.g(arguments.length)].join(""));}};ji.h=function(a,b){return a.isPointInFill(b)};ji.j=function(a,b,c){return a.isPointInFill(bi.h?bi.h(b,c):bi.call(null,b,c))};ji.H=3;var Nj=new $APP.r(null,2,[$APP.Hf,3700,$APP.Gf,600],null),Pj=new $APP.r(null,2,[$APP.Hf,4150,$APP.Gf,450],null);var Ei=new $APP.T(null,5,5,$APP.V,[new $APP.T(null,2,5,$APP.V,[6900,new $APP.T(null,2,5,$APP.V,[6800,875],null)],null),new $APP.T(null,2,5,$APP.V,[5100,new $APP.T(null,2,5,$APP.V,[4800,525],null)],null),new $APP.T(null,2,5,$APP.V,[3600,new $APP.T(null,2,5,$APP.V,[3400,475],null)],null),new $APP.T(null,2,5,$APP.V,[2E3,new $APP.T(null,2,5,$APP.V,[1700,775],null)],null),new $APP.T(null,2,5,$APP.V,[-1E3,new $APP.T(null,2,5,$APP.V,[200,500],null)],null)],null),Mj=$APP.eg/1E3,Lj=-Mj,Kj=Mj/80,Li=new $APP.T(null,
5,5,$APP.V,[new $APP.T(null,2,5,$APP.V,[0,-20],null),new $APP.T(null,2,5,$APP.V,[18,12],null),new $APP.T(null,2,5,$APP.V,[12,20],null),new $APP.T(null,2,5,$APP.V,[-12,20],null),new $APP.T(null,2,5,$APP.V,[-18,12],null)],null),Oj=vk.h(Ng(0,.015),Mg(new $APP.T(null,2,5,$APP.V,[30,400],null),new $APP.T(null,2,5,$APP.V,[.015,0],null)));var Uj=vk.h(Ng(-1,1),Mg(new $APP.T(null,2,5,$APP.V,[-1E3,1E3],null),new $APP.T(null,2,5,$APP.V,[-1,1],null))),Vj=vk.j(Ng(0,.5),Mg(new $APP.T(null,2,5,$APP.V,[1500,0],null),new $APP.T(null,2,5,$APP.V,[0,.5],null)),function(a){return Math.abs(a)});var wj=$APP.X.h(function(a){return 350/a},new $APP.T(null,3,5,$APP.V,[5E3,9E3,7E3],null));var sk=function sk(a){gh.j($APP.dg,ek,a);return window.requestAnimationFrame(sk)};var zk=["marooned","app","run"],Ak=$APP.lf;zk[0]in Ak||"undefined"==typeof Ak.execScript||Ak.execScript("var "+zk[0]);for(var Bk;zk.length&&(Bk=zk.shift());)zk.length||void 0===tk?Ak=Ak[Bk]&&Ak[Bk]!==Object.prototype[Bk]?Ak[Bk]:Ak[Bk]={}:Ak[Bk]=tk;
}).call(this);